baselines/dom.generated.d.ts, inputfiles/addedTypes.json
Fix https://github.com/Microsoft/TypeScript/issues/2044
=> Add Navigator.vibrate

baselines/dom.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/overridingTypes.json
Fix https://github.com/Microsoft/TypeScript/issues/949
=> Change the type of Image.data to Fix #949

baselines/dom.generated.d.ts, inputfiles/removedTypes.json
Fix https://github.com/Microsoft/TypeScript/issues/1253
=> Remove contains from HTMLElement

baselines/dom.generated.d.ts, inputfiles/addedTypes.json
Fixes https://github.com/Microsoft/TypeScript/issues/5813
=> Fixes Microsoft/TypeScript#5813

baselines/dom.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/addedTypes.json, inputfiles/overridingTypes.json
Fixes Microsoft/Typescript#5932
=> Added Interface and Property definitions of IndexedDB Database API

baselines/dom.generated.d.ts, inputfiles/addedTypes.json
Fixes https://github.com/Microsoft/TypeScript/issues/6096
=> Added selectedOptions Property To HTMLSelectElement

inputfiles/README.md
This will help avoid PRs where people spend time and we end up telling them that we can't accept the changes.
=> Add a 'README.md' to the 'inputfiles' directory.

baselines/dom.generated.d.ts, inputfiles/overridingTypes.json
https://github.com/Microsoft/TypeScript/issues/6106
=> To fix #6106

baselines/dom.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/overridingTypes.json
https://github.com/Microsoft/TypeScript/issues/5433
=> To fix #5433

baselines/dom.generated.d.ts, inputfiles/addedTypes.json, inputfiles/overridingTypes.json, inputfiles/removedTypes.json
fixes https://github.com/Microsoft/TypeScript/issues/6295
spec https://www.w3.org/TR/webstorage/
=> Update `StorageEvent` interface

baselines/dom.generated.d.ts, inputfiles/overridingTypes.json
Fixes https://github.com/Microsoft/TypeScript/issues/7562
=> Fix Storage interface

baselines/dom.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/addedTypes.json
Fixes https://github.com/Microsoft/TypeScript/issues/7563
=> Fix IDBDatabase interface

baselines/dom.generated.d.ts, inputfiles/addedTypes.json
=> Remove duplicated definitions for HTMLPictureElement

baselines/dom.generated.d.ts, inputfiles/overridingTypes.json
PR for [Microsoft/TypeScript#7709](https://github.com/Microsoft/TypeScript/issues/7709)
=> document.getElementsByName should return NodeListOf<HTMLElement>

Shared.fsx, TS.fsx, baselines/webworker.generated.d.ts
Fix https://github.com/Microsoft/TypeScript/issues/8091
=> Add missing types to worker

Shared.fsx, TS.fsx, baselines/dom.generated.d.ts, baselines/webworker.generated.d.ts
=> Add nullable types

baselines/dom.generated.d.ts, inputfiles/overridingTypes.json
Fixes https://github.com/Microsoft/TypeScript/issues/8320
=> Node.insertBefore requires two arguments

TS.fsx, baselines/dom.generated.d.ts, inputfiles/overridingTypes.json
=> Change the type of HTMLSelectElement.options

baselines/dom.generated.d.ts, inputfiles/addedTypes.json
=> Fix incorrect signature for HTMLCanvasElement.toBlob

baselines/dom.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/overridingTypes.json
Fixes https://github.com/Microsoft/TypeScript/issues/8101
=> try to fix https://github.com/Microsoft/TypeScript/issues/8101

baselines/dom.generated.d.ts, inputfiles/addedTypes.json
Fixes https://github.com/Microsoft/TypeScript/issues/8699
=> Add closest method of Element

baselines/dom.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/overridingTypes.json
add override function for setImmediate and setInterval;
change the order of functions of setTimeout.
=> add override function for setImmediate and setInterval

baselines/dom.generated.d.ts, inputfiles/addedTypes.json
Fixes https://github.com/Microsoft/TypeScript/issues/8866
=> Add Blob property to Window

baselines/dom.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/addedTypes.json, inputfiles/removedTypes.json
try to fix https://github.com/Microsoft/TypeScript/issues/8688
=> making IE specific declarations optional on XMLHttpRequest interface

baselines/dom.generated.d.ts, inputfiles/overridingTypes.json
=> Check type nullability in json files

baselines/dom.generated.d.ts, inputfiles/addedTypes.json
Fix https://github.com/Microsoft/TypeScript/issues/9075
=> Remove multiple Node.contains

TS.fsx, baselines/dom.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/addedTypes.json
fix #[9071](https://github.com/Microsoft/TypeScript/issues/9071).
=> add MouseWheelEvent

baselines/dom.generated.d.ts, inputfiles/addedTypes.json
Fixes https://github.com/Microsoft/TypeScript/issues/9244
=> Add conditional indexer for Canvas2DContextAttributes

TS.fsx, baselines/dom.generated.d.ts, baselines/webworker.generated.d.ts
Add this-parameters to event handler so that intellisense improves when assigning literals, and assignability checking improves when assigning functions that have this parameters themselves.
=> Add this parameters

baselines/dom.generated.d.ts, inputfiles/addedTypes.json, inputfiles/removedTypes.json
1. Add new scroll methods to Element interface
2. Move scrollIntoView method to Element from HTMLElement
3. Enable scroll methods to receive a scroll option object
=> Add scroll extension

baselines/dom.generated.d.ts, inputfiles/overridingTypes.json
Fixes https://github.com/Microsoft/TypeScript/issues/9712
=> Update Storage interface

baselines/dom.generated.d.ts, inputfiles/comments.json
fix [#10205 ](https://github.com/Microsoft/TypeScript/issues/10205)
=> fix comment of HTMLMediaElement.load()

.travis.yml, build.sh
Also includes a couple of tweaks to `build.sh` 
https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html
```
set -e === set -o errexit
set -u === set -o nounset
```
=> Add build to Travis

Shared.fsx, build.cmd, paket.lock
This changes brings down the running time from > 2 mins to 1.4 sec on my laptop ...
Lessons learned, reflection is expensive.
=> Avoid using reflection in hot spots

Shared.fsx, baselines/dom.generated.d.ts, baselines/webworker.generated.d.ts
=> Fix event type for XMLHttpRequest

baselines/dom.generated.d.ts, inputfiles/overridingTypes.json
See Microsoft/Typescript#11380.
=> Make initMouseEvent's relatedTargetArg nullable

baselines/dom.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/addedTypes.json
fix [#11510](https://github.com/Microsoft/TypeScript/issues/11510)
=> Add XMLHttpRequest.responseURL

baselines/dom.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/addedTypes.json
Fixes Microsoft/TypeScript#11581
=> Add hardwareConcurrency in Navigator

baselines/dom.generated.d.ts, inputfiles/addedTypes.json
to resolve https://github.com/Microsoft/TypeScript/issues/11589
=> Add resize to CSSStyleDeclaration

baselines/dom.generated.d.ts, inputfiles/addedTypes.json
[#10184`](https://github.com/Microsoft/TypeScript/issues/10184)
=> add canvaspattern.settransform

TS.fsx, baselines/dom.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/overridingTypes.json
Fixes https://github.com/Microsoft/TypeScript/issues/12069
=> Revert "change all DOMStringList to string[]"

baselines/dom.generated.d.ts, inputfiles/addedTypes.json
=> Add URLSearchParams

baselines/dom.generated.d.ts, inputfiles/overridingTypes.json
For issue (https://github.com/Microsoft/TypeScript/issues/13093)
=> Add "| boolean" to pixelStorei method parameter

baselines/dom.generated.d.ts, inputfiles/overridingTypes.json
For Microsoft/TypeScript#12048
=> Improve appendChild

baselines/dom.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/overridingTypes.json
Fixes Microsoft/TypeScript#13521
=> Correct the signature of console.debug

baselines/dom.generated.d.ts, inputfiles/addedTypes.json
I made a mistake in my previous pull request (https://github.com/Microsoft/TSJS-lib-generator/pull/167), I should have checked it twice.
=> Fix URLSearchParams

baselines/dom.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/addedTypes.json
Issue: https://github.com/Microsoft/TypeScript/issues/14378
=> Add signature for formData types (Fetch API)

baselines/dom.generated.d.ts, inputfiles/addedTypes.json
Fixes https://github.com/Microsoft/TypeScript/issues/14499
=> Fixes DocumentFragment missing getElementById()

baselines/dom.generated.d.ts, inputfiles/addedTypes.json
Fixes https://github.com/Microsoft/TSJS-lib-generator/issues/213 and https://github.com/Microsoft/TypeScript/issues/14363
=> Fix #213: Add index signature to HTMLCollectionOf

baselines/dom.generated.d.ts, inputfiles/addedTypes.json, inputfiles/overridingTypes.json
fixes https://github.com/Microsoft/TypeScript/issues/14435
=> Fix Touch Event Constructor

baselines/dom.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/overridingTypes.json
Add `optionalParams` to `group` and `groupCollapsed` methods of interface `Console`
=> Override Console types

baselines/dom.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/overridingTypes.json
As requested in the contrib guidelines, I've raised the relevant issue here: https://github.com/Microsoft/TypeScript/issues/15604
=> Adds static methods to Response

baselines/dom.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/overridingTypes.json
Fixes https://github.com/Microsoft/TypeScript/issues/14872, https://github.com/Microsoft/TypeScript/issues/15483
=> Update IndexedDB API

.travis.yml, paket.lock
Tracked on https://github.com/fsharp/FAKE/issues/1533
=> Update FAKE and return to Mono 5

TS.fsx, baselines/dom.generated.d.ts
Fixes #261 by removing incorrect EventHandler check.
=> Add missing events

TS.fsx
cc @zhengbli @mhegazy 
@SaschaNaz You may be able to also remove this code in your pr.
=> Remove unused code

baselines/dom.generated.d.ts, inputfiles/overridingTypes.json
fixes https://github.com/Microsoft/TypeScript/issues/15182
https://developer.mozilla.org/en/docs/Web/API/DragEvent/DragEvent
=> Override DragEvent type

baselines/dom.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/overridingTypes.json
fixes: https://github.com/Microsoft/TypeScript/issues/15988
is this enough to fix? I'm new to ts.
=> fix: DOMException missing constructor in lib.es6.d.ts

baselines/dom.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/addedTypes.json
Fixes https://github.com/Microsoft/TypeScript/issues/17758
=> Fetch API Redirected Property

baselines/dom.generated.d.ts, inputfiles/addedTypes.json
Fixes https://github.com/Microsoft/TypeScript/issues/16880
=> Added dialog element

TS.fsx, baselines/dom.generated.d.ts, baselines/webworker.generated.d.ts
Fix the issue with
1.`Promise<sequence<double>>` becoming `any`.
2. `unrestricted double` becoming `any`
=> Fix double generic types

baselines/dom.generated.d.ts, inputfiles/addedTypes.json
It's missing in the IDL file.
https://wicg.github.io/IntersectionObserver/#intersection-observer-entry
=> Add isIntersecting key to IntersectionObserverEntry

baselines/dom.generated.d.ts, inputfiles/overridingTypes.json
Fix for Microsoft/TypeScript#16543
=> Change to nullable type for form property of form associated elements

baselines/dom.generated.d.ts, inputfiles/overridingTypes.json
Fixes https://github.com/Microsoft/TypeScript/issues/17921
=> Fix Document.currentScript

baselines/dom.generated.d.ts, inputfiles/overridingTypes.json
Explanation in Microsoft/TypeScript#17590
=> Fix getRegistration in ServiceWorkerContainer

baselines/dom.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/addedTypes.json
To resolve https://github.com/Microsoft/TypeScript/issues/18524
=> Change EcKeyImportParams to extend Algorithm

README.md, baselines/dom.generated.d.ts, inputfiles/addedTypes.json
As reported in TypeScript issue #19024:
https://github.com/Microsoft/TypeScript/issues/19024
Spec here:
https://www.w3.org/2011/tracking-protection/drafts/tracking-dnt.html#widl-Navigator-doNotTrack
=> Add doNotTrack property on Navigator

baselines/dom.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/addedTypes.json, inputfiles/overridingTypes.json, inputfiles/removedTypes.json
Fixes #289
Fixes Microsoft/TypeScript#19656
=> Fixed fetch API's HeadersInit, RequestInit and ResponseInit typedef

baselines/dom.generated.d.ts, inputfiles/overridingTypes.json
Related #310, should not drop old spec immediately (my mistake) 🙏
=> Support old spec

baselines/dom.generated.d.ts, inputfiles/overridingTypes.json
Issue: https://github.com/Microsoft/TypeScript/issues/20065
=> Fix getRegistration's parameter

baselines/dom.generated.d.ts, inputfiles/overridingTypes.json
Fixes Microsoft/TypeScript#19195
=> add overrides for CanvasRenderingContext2D methods with Path2D param

TS.fsx, baselines/dom.generated.d.ts
Address comment from https://github.com/Microsoft/TypeScript/pull/20213
=> Add @deprecation notice

baselines/dom.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/overridingTypes.json
=> Allow URL Object as constructor's base parameter

baselines/dom.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/addedTypes.json, inputfiles/overridingTypes.json
Also change `lastModifiedDate` type to `Date`
Fixes Microsoft/TypeScript#20354
=> Add File.lastModified Definition

baselines/dom.generated.d.ts, inputfiles/overridingTypes.json
fixes [#20977](https://github.com/Microsoft/TypeScript/issues/20977)
=> change getAttributeNode and getAttributeNodeNS

baselines/dom.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/overridingTypes.json
related: https://github.com/Microsoft/TSJS-lib-generator/pull/349
Hope this is finally ok :\
=> listener argument is mandatory

TS.fsx, baselines/dom.generated.d.ts, inputfiles/addedTypes.json
related https://github.com/DefinitelyTyped/DefinitelyTyped/pull/13045
https://w3c.github.io/webcomponents/spec/custom/
https://dom.spec.whatwg.org/#dom-document-createelement
=> Add Custom Elements v1 typings

baselines/dom.generated.d.ts, inputfiles/addedTypes.json
Fixes https://github.com/Microsoft/TypeScript/issues/21432.
=> stylesheets -> styleSheets

baselines/dom.generated.d.ts, inputfiles/addedTypes.json
for TypeScript issue [#21353](https://github.com/Microsoft/TypeScript/issues/21353)
=> adds onvisibilitychange to Document

baselines/dom.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/overridingTypes.json
fix https://github.com/Microsoft/TypeScript/issues/21266
=> Fix WebSocket.send method

baselines/dom.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/overridingTypes.json
Fixes https://github.com/Microsoft/TypeScript/issues/21420
=> Revert the type of `ForEachCallback` parameter to `any`

baselines/dom.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/addedTypes.json
Added web animation types based on [this](https://developer.mozilla.org/en-US/docs/Web/API/Animation/Animation)
Fixes Microsoft/TypeScript#21492
=> add web-animations types

baselines/dom.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/overridingTypes.json
Fixes https://github.com/Microsoft/TypeScript/issues/21821
=> PushManager getSubscription possibly null

baselines/dom.generated.d.ts, inputfiles/addedTypes.json
Closes: https://github.com/Microsoft/TypeScript/issues/20489
=> screen: add `lockOrientation` and `unlockOrientation`

baselines/dom.generated.d.ts, inputfiles/addedTypes.json, inputfiles/overridingTypes.json
=>  Fix #377: use interface instead of a typedef for `AnimationKeyFrame`

baselines/dom.generated.d.ts, inputfiles/addedTypes.json, inputfiles/overridingTypes.json
According to MDN: https://developer.mozilla.org/en-US/docs/Web/API/MutationRecord
https://github.com/Microsoft/TypeScript/issues/22179
=> update MutationRecord type

baselines/dom.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/addedTypes.json, inputfiles/overridingTypes.json
Fix Microsoft/TypeScript#22943
Fix Microsoft/TypeScript#22916
Fix Microsoft/TypeScript#22917
=> Few fixes for TS 2.8.2

baselines/dom.generated.d.ts, inputfiles/overridingTypes.json
https://github.com/Microsoft/TypeScript/issues/10379
=> Fix https://github.com/Microsoft/TypeScript/issues/10379#issuecomment-376966533:  Make `Window.opener` wirable

baselines/dom.generated.d.ts, inputfiles/overridingTypes.json
[Microsoft/TypeScript#22322](https://github.com/Microsoft/TypeScript/issues/22322)
=> Include Node.isConnected

baselines/dom.generated.d.ts, inputfiles/overridingTypes.json
[Microsoft/TypeScript#/21256](https://github.com/Microsoft/TypeScript/issues/21256)
=> Add textTracks SourceBuffer

baselines/dom.generated.d.ts, inputfiles/overridingTypes.json
[Microsoft/TypeScript#23107](https://github.com/Microsoft/TypeScript/issues/23107)
[w3#dom-document-readystate](https://www.w3.org/TR/html50/dom.html#dom-document-readystate)
[whatwg#dom-document-readystate](https://html.spec.whatwg.org/multipage/dom.html#dom-document-readystate)
=> Change readyState from string to DocumentReadyState

baselines/dom.generated.d.ts, src/emitter.ts
Alternative fix for Microsoft/TypeScript#23160
Supersedes: https://github.com/Microsoft/TSJS-lib-generator/pull/408
=> Handel `Sequence<float>` => `Float32Array`

baselines/dom.generated.d.ts, inputfiles/overridingTypes.json
[Microsoft/TypeScript#23057](https://github.com/Microsoft/TypeScript/issues/23057)
[w3#WebCryptoAPI](https://www.w3.org/TR/WebCryptoAPI)
=> 23057 - Fix WebCrypto Algorithm params

baselines/dom.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/addedTypes.json, inputfiles/idl/Indexed Database.widl, inputfiles/idlSources.json, inputfiles/knownWorkerTypes.json, src/emitter.ts, src/widlprocess.ts
Adds some new methods, events, etc.
=> Add IndexedDB types

baselines/dom.es6.generated.d.ts, baselines/dom.generated.d.ts, inputfiles/addedTypes.json, inputfiles/idl/Geometry Interfaces.widl, inputfiles/idl/Navigation Timing.widl, inputfiles/idlSources.json, src/emitter.ts
Adds DOMRectReadOnly.toJSON and other new types.
=> Add Geometry Interfaces types

src/index.ts, src/widlprocess.ts
This fixes partial dictionary problem in #424.
=> Merge partial dictionaries

baselines/dom.generated.d.ts, inputfiles/addedTypes.json, inputfiles/idl/WebRTC.widl, inputfiles/idlSources.json, inputfiles/overridingTypes.json, inputfiles/removedTypes.json, package-lock.json, src/fetcher.ts
[TypeScript#23300](https://github.com/Microsoft/TypeScript/issues/23300)
[webrtc#dom-rtcdatachannel](https://www.w3.org/TR/webrtc/#dom-rtcdatachannel)
=> Add RTCDataChannel interface

baselines/dom.generated.d.ts, src/emitter.ts
=> Use number[]|Float32Array union

baselines/dom.generated.d.ts, inputfiles/addedTypes.json
These two ParentNodes tends to create needless changes, reordering each other. Merging them is a correct thing to do and will remove git noises.
=> Merge two ParentNode interfaces

baselines/dom.generated.d.ts, inputfiles/addedTypes.json, inputfiles/overridingTypes.json
Some dictionary types in addedTypes.json are incorrectly defined as interfaces with no-interface-object, so this PR fixes them. Also, HTMLegendElement is just a typo and the corrected type is already there.
=> Correct dictionary types

inputfiles/addedTypes.json, inputfiles/overridingTypes.json
They have no effect on the lib generation.
=> Remove redundant types from added/overrideTypes

baselines/dom.generated.d.ts, inputfiles/overridingTypes.json
This fixes Microsoft/TypeScript#23646
=> Use generic for getRandomValues

baselines/dom.generated.d.ts, inputfiles/idl/Geometry Interfaces.widl, inputfiles/idl/Pointer Events.widl, inputfiles/idlSources.json
Adds two new PointerEvent fields and a static method hasPointerCapture.
=> Add Pointer Events types

baselines/dom.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/idl/Geometry Interfaces.widl, inputfiles/idl/HTML - Common DOM interfaces.widl, inputfiles/idlSources.json, inputfiles/overridingTypes.json, src/emitter.ts, src/types.d.ts, src/widlprocess.ts
Adds support for anonymous method types, adds RadioNodeList.
=> Add HTML common DOM interface types

baselines/dom.es6.generated.d.ts, baselines/dom.generated.d.ts, inputfiles/comments.json, inputfiles/idl/Geometry Interfaces.widl, inputfiles/idl/HTML - Form control infrastructure.widl, inputfiles/idl/HTML - Form elements.widl, inputfiles/idlSources.json, inputfiles/overridingTypes.json, src/widlprocess.ts
Adds `labels`, `reportValidity()`, etc.
=> Add Form elements types

baselines/dom.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/idl/Storage.widl, inputfiles/idlSources.json, src/fetcher.ts
This adds `navigator.storage` and `StorageManager`.
=> Add Storage types

baselines/dom.es6.generated.d.ts, baselines/dom.generated.d.ts, inputfiles/idl/Web Audio.widl, inputfiles/idl/Worklets.widl, inputfiles/idlSources.json, inputfiles/overridingTypes.json, src/emitter.ts, src/index.ts
Fixes some invalidly empty constructors.
=> Add Web Audio types

baselines/dom.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/overridingTypes.json
Fixes Microsoft/TypeScript#23653
=> override Worker.postMessage deprecation flag

baselines/dom.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/addedTypes.json, inputfiles/idl/Web Messaging.widl, inputfiles/idlSources.json
[Microsoft/TypeScript#24059](https://github.com/Microsoft/TypeScript/issues/24059)
=> Add WebMessaging types

package-lock.json, package.json
=> Update webidl2 to 13.0.2

baselines/dom.generated.d.ts, inputfiles/overridingTypes.json
Fixes [TypeScript#24633](https://github.com/Microsoft/TypeScript/issues/24633)
=> 24633 - Update Node interface

baselines/dom.generated.d.ts, baselines/webworker.generated.d.ts, src/emitter.ts
Fixes [TypeScript#24717](https://github.com/Microsoft/TypeScript/issues/24717)
=> Emitter ignores nullable arguments

baselines/dom.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/overridingTypes.json, package-lock.json
Fixes [24869](https://github.com/Microsoft/TypeScript/issues/24869)
=> Update console.profileEnd type definition

README.md
Baseline files copy command update in docs.
=> Baseline files update - docs

baselines/dom.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/addedTypes.json, inputfiles/idl/Page Visibility.widl, inputfiles/idlSources.json
=> Add Page Visibility types

baselines/dom.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/addedTypes.json, inputfiles/idl/HTML - Communication.commentmap.json, inputfiles/idl/HTML - Communication.widl, inputfiles/idl/Web Animations.widl, inputfiles/idlSources.json, inputfiles/overridingTypes.json, src/helpers.ts
...and updates some Web Animations return types.
=> Add HTML communication types

package-lock.json, src/helpers.ts
Fixes https://github.com/Microsoft/TSJS-lib-generator/issues/516
=> Add generic type parameter to filterProperties

baselines/dom.generated.d.ts, inputfiles/idl/Identity for WebRTC.widl, inputfiles/idl/WebRTC.widl, inputfiles/idlSources.json, package-lock.json
As the WebRTC spec has been split into two specs.
=> Add Identity for WebRTC types

baselines/dom.generated.d.ts, inputfiles/idl/HTML - Canvas.widl, src/fetcher.ts
whatwg/html#3764 breaks fetcher.ts so this fixes it.
=> Fix fetch error from HTML

baselines/dom.generated.d.ts, inputfiles/overridingTypes.json
Fixes https://github.com/Microsoft/TypeScript/issues/26083
=> Add index signature back to `Storage`

baselines/dom.generated.d.ts, inputfiles/addedTypes.json
=> Changed returned type of Element.getElementsByClassName to HTMLCollectionOf<Element>

baselines/dom.generated.d.ts, inputfiles/overridingTypes.json
=> Fix #549: Add index signature for `HTMLFormElement`

baselines/dom.generated.d.ts, inputfiles/overridingTypes.json
=> Make addListener signature more specific

baselines/dom.generated.d.ts, inputfiles/addedTypes.json
First time doing this, so not sure if everything is correct. Would appreciate a point in the right direction if I'm doing this wrong!
Fixes https://github.com/Microsoft/TypeScript/issues/26081
=> Add HTMLDialogElement DOM Typing

baselines/dom.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/comments.json, inputfiles/idl/Fetch.commentmap.json
https://github.com/Microsoft/TypeScript/issues/27528
=> Removed duplicate "the" from documentation

src/widlprocess.ts
Fix #573 
This is a first PR, so if there are any problems, please tell me 🙇
=> fix build error

baselines/dom.generated.d.ts, inputfiles/addedTypes.json
Related https://github.com/Microsoft/TypeScript/issues/24001
I added SVGCursorElemet type.
If there are any problems, please tell me 🙇
=> Add SVGCursorElement type

baselines/dom.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/addedTypes.json, inputfiles/overridingTypes.json, src/emitter.ts, src/types.d.ts
=> Mark added types as deprecated

inputfiles/idl/CSS Animations.widl, inputfiles/idl/CSS Transitions.widl, inputfiles/idl/HTML - DOM.widl, inputfiles/idl/Pointer Events.widl, inputfiles/idl/Push.widl, inputfiles/idl/SVG - Basic Data Types and Interfaces.widl
Update some IDLs that is changed but not really affects TS output.
=> Equivalent IDL update

baselines/dom.generated.d.ts, inputfiles/addedTypes.json
Related Microsoft/TypeScript#24001
I added SVGAnimateElement, SVGAnimateMotionElement, SVGAnimateTransformElement.
If there are any problems, please tell me 🙇
=> Add some svg animation types

baselines/dom.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/addedTypes.json, inputfiles/knownTypes.json, inputfiles/overridingTypes.json
closes https://github.com/Microsoft/TypeScript/issues/28136
=> webworker: expose WorkerOptions parameter on constructor

baselines/dom.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/addedTypes.json, inputfiles/idl/Geometry Interfaces.widl
Fixes Microsoft/TypeScript#26111
A change by w3c/fxtf-drafts#318.
=> Add DOMMatrix.scaleNonUniform()

baselines/dom.generated.d.ts, inputfiles/comments.json, inputfiles/overridingTypes.json, package-lock.json
Fixes https://github.com/Microsoft/TSJS-lib-generator/issues/642
CC: @saschanaz Please review.
=> Fix valueAsDate to be Date | null

baselines/dom.generated.d.ts, inputfiles/idl/CSS Basic User Interface.widl, inputfiles/idlSources.json
=> Add CSS Basic User Interface types 

baselines/dom.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/idl/Encoding.commentmap.json, inputfiles/idl/Encoding.widl
Adds TextDecoderStream/TextEncoderStream.
=> Add Encoding stream APIs

baselines/dom.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/idl/WebAssembly JavaScript Interface.widl, inputfiles/idlSources.json, inputfiles/overridingTypes.json, package.json, src/emitter.ts, src/expose.ts, src/helpers.ts, src/legacy-namespace.ts, src/types.d.ts, src/widlprocess.ts
=> Add WebAssembly types

inputfiles/idl/Fetch.widl, inputfiles/idl/Gamepad.widl, inputfiles/idl/HTML - Embedded content.commentmap.json, inputfiles/idl/HTML - Offline Web applications.widl, inputfiles/idl/Pointer Events.widl, inputfiles/idl/User Timing.widl
Applies changes from upstream with no real effect for code generation.
=> Apply insignificant IDL updates

baselines/dom.generated.d.ts, inputfiles/addedTypes.json, inputfiles/idl/CSS Will Change.widl, inputfiles/idlSources.json
Fixes https://github.com/Microsoft/TypeScript/issues/29620
=> Fixes Microsoft/TypeScript#29620

baselines/dom.generated.d.ts, inputfiles/overridingTypes.json
Fixes Microsoft/TypeScript#30042.
=> Make postMessage's 2nd param, targetOrigin, optional

baselines/dom.generated.d.ts, inputfiles/addedTypes.json
Accidentally removed by #676 @sandersn
=> Restore SVG <polygon>/<polyline>

baselines/dom.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/overridingTypes.json, inputfiles/removedTypes.json
We now have a Chrome implementation.
=> Expose OffscreenCanvas types

baselines/dom.generated.d.ts, inputfiles/addedTypes.json
Fixes https://github.com/Microsoft/TypeScript/issues/29995
=> Fix auxclick event type

baselines/dom.generated.d.ts, inputfiles/idl/CSS Transforms.widl, inputfiles/idlSources.json
Adds `transform-box` CSS property.
=> Add CSS Transforms types

baselines/dom.generated.d.ts, baselines/dom.iterable.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/addedTypes.json, inputfiles/idl/CSS Conditional Rules.widl, inputfiles/idl/CSS Object Model.widl, inputfiles/idlSources.json, inputfiles/overridingTypes.json, inputfiles/removedTypes.json, src/emitter.ts, src/index.ts, src/widlprocess.ts
~~*Note: This includes types that should be excluded because of implementation problem. You must first check if there are multiple stable implementations when you open a PR.*~~
~~Anyone who wants to boost merging CSS types might do some cherrypicking from here.~~
Now ready to get a review.
=> Add CSSOM/Conditional Rules types

baselines/dom.generated.d.ts, inputfiles/overridingTypes.json
fixes microsoft/TypeScript#36965
=> Recrate #833 from scratch to avoid CLA issues

baselines/dom.generated.d.ts, inputfiles/removedTypes.json
- [WHATWG spec](https://html.spec.whatwg.org/multipage/interaction.html#attr-enterkeyhint)
- [Chrome Platform Status](https://www.chromestatus.com/feature/5654529808793600)
- [MDN compat PR](https://github.com/mdn/browser-compat-data/pull/5990)
- [MDN request for page](https://github.com/mdn/sprints/issues/3109)
=> feat: Add enterKeyHint

baselines/dom.generated.d.ts, inputfiles/idl/CSS Overscroll Behavior.widl, inputfiles/idlSources.json
Adding the CSS overscoll-behavior property. This should fix issue #824
=> Added CSS overscroll-behavior

baselines/dom.generated.d.ts, inputfiles/idl/HTML - Embedded content.widl, inputfiles/idl/HTML - Form elements.widl, inputfiles/idl/HTML - Media.widl, src/widlprocess.ts
This also adds [`HTMLImageElement#loading`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/loading).
=> Support [LegacyFactoryFunction]

package.json, src/widlprocess.ts
This fixes build failures.
Fixes #903, closes #904
=> Pin to typescript 20200908

baselines/dom.generated.d.ts, inputfiles/comments.json
Fixes #https://github.com/microsoft/TypeScript/issues/40874.
=> Removed incorrect info from getElementById comment

baselines/dom.generated.d.ts, inputfiles/addedTypes.json, inputfiles/idl/UI Events.widl, inputfiles/idlSources.json
As now we have keyCode too (#892)
=> Add deprecated KeyboardEventInit.charCode

deploy/deployChangedPackages.mjs, inputfiles/README.md
@saschanaz should be able to merge this
=> 2nd Minor PR

.github/CODEOWNERS, .github/workflows/codeowners-merge.yml
Bug fixes for the 'maintainers' label stuff
=> Bump codeowners action to 1.5.4

baselines/dom.generated.d.ts, inputfiles/addedTypes.json, inputfiles/removedTypes.json
=> Restore WebGLRenderingContextBase#canvas

baselines/dom.generated.d.ts, baselines/serviceworker.generated.d.ts, baselines/sharedworker.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/addedTypes.json, src/build.ts, src/build/emitter.ts, src/build/types.d.ts
No more mixed deprecation notes in `comment`.
=> Allow strings in deprecated field

.github/workflows/test_typescript.yml
Should reduce CI times for a some PRs
=> Don't run the TS tests unless baselines change

baselines/dom.generated.d.ts, inputfiles/addedTypes.jsonc
=> Restore `document.caretRangeFromPoint()`

baselines/dom.generated.d.ts, src/build/bcd.ts
This is kinda new, @orta @sandersn do you think this is good to have?
=> Mark legacy aliases with @deprecated

inputfiles/overridingTypes.jsonc
Addresses some tech debt @saschanaz brought up in https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/1088#discussion_r681360802.
I don't necessarily know if I got everything, but I figure it's a good start.
=> Remove unnecessary 'name' properties.

baselines/dom.generated.d.ts, src/build/emitter.ts
Fixes a clipboard type issue reported in #1029.
=> Track typedefs and generics when resolving promises

baselines/dom.generated.d.ts, inputfiles/addedTypes.jsonc
=> Use SubmitEvent for submit event

.github/workflows/deploy.yml
This should mean that merged PRs via code-owners-self-merge trigger a deploy (eventually)
=> Run the deploy every night

baselines/dom.generated.d.ts, inputfiles/addedTypes.jsonc, src/build/emitter.ts, src/build/helpers.ts
Fixes [#41212](https://github.com/microsoft/TypeScript/pull/41212) and [#41334](https://github.com/microsoft/TypeScript/issues/41334)
=> fix(41212,41334): removed duplicate interface extensions

baselines/dom.generated.d.ts, inputfiles/addedTypes.jsonc
=> Remove `navigator.pointerEnabled`

deploy/deployChangedPackages.js
Currently release notes are generated only for `.iterable`s, because of a regression from #1084 😬
This also removes hackish `\n` from title and makes sure things have double newlines between each other.
=> Show change for all files

baselines/dom.generated.d.ts, package-lock.json, src/build/utils/fs.ts, src/test.ts
=> Manually update to bcd@4.0.1

.github/workflows/update-core-deps.yml
=> Push to typescript-bot fork

.github/workflows/codeowners-merge.yml
To https://github.com/OSS-Docs-Tools/code-owner-self-merge/releases/tag/1.6.1
=> Update self-merging automation

baselines/dom.generated.d.ts, baselines/serviceworker.generated.d.ts, baselines/sharedworker.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/overridingTypes.jsonc
=> Use null for RequestInit.window

baselines/dom.generated.d.ts, package-lock.json
=> Manually update to bcd@4.0.4

.github/workflows/update-core-deps.yml
Since #1170 worked perfectly and opened #1171 🎉
=> Remove forking action

baselines/dom.generated.d.ts, baselines/serviceworker.generated.d.ts, baselines/sharedworker.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/overridingTypes.jsonc
Addresses undocumented breaking change mentioned in this [comment](https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1029#issuecomment-898868533)
[Issue#1186](https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1186)
=> adding CryptoKeyPair override

.github/workflows/ci.yml, .github/workflows/deploy.yml, .github/workflows/pr-to-typescript.yml, .github/workflows/test_typescript.yml, .github/workflows/update-core-deps.yml, README.md
`@2` has been there for a year, and `cache` is actually not supported in `@1`.
=> Use actions/setup-node@2 with `lts/*`

baselines/dom.generated.d.ts, baselines/dom.iterable.generated.d.ts, baselines/serviceworker.generated.d.ts, baselines/sharedworker.generated.d.ts, baselines/webworker.generated.d.ts, package-lock.json
=> Update to bcd@4.1.3

baselines/dom.generated.d.ts, baselines/serviceworker.generated.d.ts, baselines/sharedworker.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/overridingTypes.jsonc
The return of encrypt/decrypt is currently `Promise<any>`, this fixes the issue, i think?
=> fix SubtleCrypto encrypt/decrypt return

inputfiles/removedTypes.jsonc, src/build/bcd.ts, src/build/expose.ts
No need to remove empty mixins manually anymore.
=> Automatically trim redundant mixins

.github/codeql/codeql-configuration.yml, .github/workflows/codeql.yml
=> Add CodeQL scanning

baselines/dom.generated.d.ts, inputfiles/removedTypes.jsonc, package-lock.json
=> Manually update to idl@3.22.5

baselines/dom.generated.d.ts, package-lock.json
Closes #1457
Closes #1458 
Closes #1459 
Closes #1460 
Closes #1461 
Closes #1463
=> Manually update to webref/idl@3.23.0

baselines/dom.generated.d.ts, inputfiles/removedTypes.jsonc, package-lock.json
=> Manually update to webref/idl 3.28.0

baselines/dom.generated.d.ts, baselines/serviceworker.generated.d.ts, baselines/sharedworker.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/removedTypes.jsonc, package-lock.json
=> Manually update to bcd@5.2.52

baselines/dom.generated.d.ts, inputfiles/overridingTypes.jsonc
This reverts commit b24e2d7a9d73ce657d9eddf1b1c49597812b61ee.
=> Revert "make location.reload() return never (#1544)"

baselines/audioworklet.generated.d.ts, baselines/dom.generated.d.ts, baselines/serviceworker.generated.d.ts, baselines/sharedworker.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/addedTypes.jsonc, inputfiles/overridingTypes.jsonc, package-lock.json, package.json, src/build/bcd/mapper.ts, src/build/utils/record.ts
With some hack to mitigate https://github.com/mdn/browser-compat-data/issues/20114.
Closes #1569
=> Update to bcd@5.2.64

baselines/dom.generated.d.ts, baselines/dom.iterable.generated.d.ts, baselines/serviceworker.generated.d.ts, baselines/serviceworker.iterable.generated.d.ts, baselines/sharedworker.generated.d.ts, baselines/sharedworker.iterable.generated.d.ts, baselines/webworker.generated.d.ts, baselines/webworker.iterable.generated.d.ts, inputfiles/removedTypes.jsonc, package-lock.json
Closes #1625 
Mostly about replacing some GLuint uses to number, and adding MouseEvent.layerX/layerY.
=> Manually update to idl@3.39.0

baselines/audioworklet.generated.d.ts, baselines/dom.generated.d.ts, baselines/serviceworker.generated.d.ts, baselines/sharedworker.generated.d.ts, baselines/webworker.generated.d.ts, package-lock.json, src/build/bcd/keep-alive.ts, src/build/bcd/mapper.ts, src/build/utils/record.ts
=> Update to bcd@5.4.1

baselines/dom.generated.d.ts, inputfiles/addedTypes.jsonc
=> Fix OverconstrainedError superclass

baselines/dom.generated.d.ts, baselines/serviceworker.generated.d.ts, baselines/sharedworker.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/overridingTypes.jsonc, inputfiles/removedTypes.jsonc, package-lock.json
=> Update to webref/idl@3.44.3

baselines/audioworklet.asynciterable.generated.d.ts, baselines/audioworklet.generated.d.ts, baselines/dom.asynciterable.generated.d.ts, baselines/dom.generated.d.ts, baselines/serviceworker.asynciterable.generated.d.ts, baselines/serviceworker.generated.d.ts, baselines/sharedworker.asynciterable.generated.d.ts, baselines/sharedworker.generated.d.ts, baselines/webworker.asynciterable.generated.d.ts, baselines/webworker.generated.d.ts, package-lock.json
ReadableStream is finally async-iterable! 🎉 
Fixes #1677
=> Update to bcd@5.5.21

.github/dependabot.yml, .github/workflows/update-core-deps.yml, package-lock.json, package.json
Also removing one unused dependency.
=> Exclude @mdn/@webref from dependabot updates

.github/workflows/update-core-deps.yml
=> Give bot token to onUpdateFailure step

.github/workflows/codeowners-merge.yml
Didn't realize this workflow could close issues too. https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1029#issuecomment-2328408718
=> Allow codeowners-merge to touch issues

baselines/dom.generated.d.ts, baselines/serviceworker.generated.d.ts, baselines/sharedworker.generated.d.ts, baselines/ts5.5/dom.generated.d.ts, baselines/ts5.5/serviceworker.generated.d.ts, baselines/ts5.5/sharedworker.generated.d.ts, baselines/ts5.5/webworker.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/overridingTypes.jsonc, package-lock.json
Thanks bot, https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1282#issuecomment-2401639814
=> Manually update to bcd@5.6.5

baselines/dom.generated.d.ts, baselines/ts5.5/dom.generated.d.ts, inputfiles/overridingTypes.jsonc
=> Manually remove some deprecations

baselines/dom.generated.d.ts, inputfiles/overridingTypes.jsonc, src/build.ts, src/build/emitter.ts
This is enabled for TS 5.1+ but not worth adding a new set of files.
=> Support [PutForwards] for TS>5.5

baselines/dom.generated.d.ts, baselines/dom.iterable.generated.d.ts, baselines/ts5.5/dom.generated.d.ts, baselines/ts5.5/dom.iterable.generated.d.ts, inputfiles/overridingTypes.jsonc, package-lock.json
Thanks bot https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1282#issuecomment-2458955629
=> Manually update to bcd@5.6.13

baselines/dom.generated.d.ts, baselines/serviceworker.generated.d.ts, baselines/sharedworker.generated.d.ts, baselines/ts5.5/dom.generated.d.ts, baselines/ts5.5/serviceworker.generated.d.ts, baselines/ts5.5/sharedworker.generated.d.ts, baselines/ts5.5/webworker.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/overridingTypes.jsonc, inputfiles/removedTypes.jsonc, package-lock.json
=> Manually update to idl@3.56.1 and bcd@5.6.17

baselines/dom.generated.d.ts, baselines/serviceworker.generated.d.ts, baselines/sharedworker.generated.d.ts, baselines/ts5.5/dom.generated.d.ts, baselines/ts5.5/serviceworker.generated.d.ts, baselines/ts5.5/sharedworker.generated.d.ts, baselines/ts5.5/webworker.generated.d.ts, baselines/webworker.generated.d.ts, package-lock.json
(No build failures, just because #1865)
=> Manually update to bcd@5.6.26

inputfiles/overridingTypes.jsonc, src/build/emitter.ts, src/build/types.d.ts
Ultimately we should add type parameter to all mixins with event handlers.
Fixes #1883
=> Automate overrideImplements

baselines/dom.generated.d.ts, baselines/ts5.5/dom.generated.d.ts, inputfiles/removedTypes.jsonc, package-lock.json
=> Update to idl@3.59.1

baselines/audioworklet.generated.d.ts, baselines/dom.generated.d.ts, baselines/serviceworker.generated.d.ts, baselines/sharedworker.generated.d.ts, baselines/ts5.5/audioworklet.generated.d.ts, baselines/ts5.5/dom.generated.d.ts, baselines/ts5.5/serviceworker.generated.d.ts, baselines/ts5.5/sharedworker.generated.d.ts, baselines/ts5.5/webworker.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/removedTypes.jsonc, package-lock.json
=> Update to bcd@5.6.37

baselines/dom.generated.d.ts, baselines/serviceworker.generated.d.ts, baselines/sharedworker.generated.d.ts, baselines/ts5.5/dom.generated.d.ts, baselines/ts5.5/serviceworker.generated.d.ts, baselines/ts5.5/sharedworker.generated.d.ts, baselines/ts5.5/webworker.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/overridingTypes.jsonc, package-lock.json
https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1282#issuecomment-2720318818, good bot.
=> Manually update to idl@3.61.1

inputfiles/README.md
I have removed it because it doesn't exists
=> Chore remove `browser.webidl.preprocessed.json`

.github/workflows/codeowners-merge.yml
I have the bandwidth to look at stuff here.
(Remove orta (sorry) since that doesn't work anymore)
=> Add jakebailey to maintainer assignment set

baselines/dom.generated.d.ts, baselines/serviceworker.generated.d.ts, baselines/sharedworker.generated.d.ts, baselines/ts5.5/dom.generated.d.ts, baselines/ts5.5/serviceworker.generated.d.ts, baselines/ts5.5/sharedworker.generated.d.ts, baselines/ts5.5/webworker.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/overridingTypes.jsonc, package-lock.json, package.json
This is a major version bump that needs Microsoft approval.
=> Upgrade to BCD 6

deploy/createTypesPackages.js
=> feat: Add types for Web Worker to types packages

deploy/createTypesPackages.js
=> chore: add the asynciterable version of the files

baselines/dom.generated.d.ts, baselines/ts5.5/dom.generated.d.ts, baselines/ts5.6/dom.generated.d.ts, inputfiles/addedTypes.jsonc
fixes #1997
I have made it not deprecated
=> Remove deprecated HTMLDocument interface and related comments

baselines/dom.generated.d.ts, baselines/ts5.5/dom.generated.d.ts, baselines/ts5.6/dom.generated.d.ts, inputfiles/overridingTypes.jsonc
=> RadioNodeList should extend NodeListOf<HTMLInputElement>

baselines/dom.iterable.generated.d.ts, baselines/serviceworker.iterable.generated.d.ts, baselines/sharedworker.iterable.generated.d.ts, baselines/ts5.5/dom.iterable.generated.d.ts, baselines/ts5.5/serviceworker.iterable.generated.d.ts, baselines/ts5.5/sharedworker.iterable.generated.d.ts, baselines/ts5.5/webworker.iterable.generated.d.ts, baselines/ts5.6/dom.iterable.generated.d.ts, baselines/ts5.6/serviceworker.iterable.generated.d.ts, baselines/ts5.6/sharedworker.iterable.generated.d.ts, baselines/ts5.6/webworker.iterable.generated.d.ts, baselines/webworker.iterable.generated.d.ts, src/build/emitter.ts
=> Emit Iterable only for non-return array types

inputfiles/overridingTypes.jsonc
=> Remove unneeded elements

baselines/dom.generated.d.ts, baselines/ts5.5/dom.generated.d.ts, baselines/ts5.6/dom.generated.d.ts, inputfiles/removedTypes.jsonc
fixes #2156 
I didn't add delay, and trackVisibility because they are only available for Blink.
=> Adds Scroll margin

baselines/dom.generated.d.ts, baselines/serviceworker.generated.d.ts, baselines/sharedworker.generated.d.ts, baselines/ts5.5/dom.asynciterable.generated.d.ts, baselines/ts5.5/serviceworker.asynciterable.generated.d.ts, baselines/ts5.5/sharedworker.asynciterable.generated.d.ts, baselines/ts5.5/webworker.asynciterable.generated.d.ts, baselines/ts5.6/dom.asynciterable.generated.d.ts, baselines/ts5.6/serviceworker.asynciterable.generated.d.ts, baselines/ts5.6/sharedworker.asynciterable.generated.d.ts, baselines/ts5.6/webworker.asynciterable.generated.d.ts, baselines/ts5.9/dom.asynciterable.generated.d.ts, baselines/ts5.9/serviceworker.asynciterable.generated.d.ts, baselines/ts5.9/sharedworker.asynciterable.generated.d.ts, baselines/ts5.9/webworker.asynciterable.generated.d.ts, baselines/webworker.generated.d.ts, inputfiles/overridingTypes.jsonc
Relates to https://github.com/DefinitelyTyped/DefinitelyTyped/pull/73820
=> Use union for FileSystemDirectoryHandle
