TS.fsx
inputfiles/sample.json

For added interfaces in the json files, if there is a `constructorSignature` string array property, they will be incorporated in the emitted file.

Add support for constructors in added interface json file

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.json

Fix https://github.com/Microsoft/TypeScript/issues/3583

Overwrite return types for HTMLTableElement, HTMLTableSectionElement, and HTMLTableRowElement methods

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json

Fix https://github.com/Microsoft/TypeScript/issues/5199

Add HTMLTemplateDocument

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/overridingTypes.json

Fixes Microsoft/Typescript#5832

Added correct definition for createIndex method of IDBObjectStore

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.json

This fixes Microsoft/TypeScript#4407, which was reported as being an error on `HTMLElement`. The actual error was with `Element`.

Mark Element.setAttribute's parameters as required

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json

Hi
This fixes https://github.com/Microsoft/TypeScript/issues/5816
This is my first PR, would be good if someone can give feedback. thanks

Add property of AudioContext state API

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.json

[The WebIDL file](https://github.com/Microsoft/TSJS-lib-generator/blob/472b4b1921d2b58ed8ae6505119d336d706ad972/inputfiles/browser.webidl.xml#L3747), reports `HTMLMediaElement.readyState` to be of type `any`. According to [the specification](https://html.spec.whatwg.org/multipage/embedded-content.html#htmlmediaelement) however, it should be of type `unsigned short` (which translates to `number` in TypeScript).
This PR adds an override for `HTMLMediaElement.readyState`.

Override type of HTMLMediaElement.readyState

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json

Proposed fix for https://github.com/Microsoft/TypeScript/issues/5754

Add Element.innnerHTML

---

JS.fsx
TS.fsx
baselines/dom.generated.d.ts

`MediaSource.readyState` is a [`ReadyState` string enum](https://w3c.github.io/media-source/#idl-def-ReadyState), but TypeScript [reports it](https://github.com/Microsoft/TSJS-lib-generator/blob/e9be0cb8e95e2a4b998cc0a658675127aac35e17/baselines/dom.generated.d.ts#L7641) to be a `number`.

ReadyState type is a string

---

TS.fsx

Related to https://github.com/Microsoft/TypeScript/issues/5773
This fix enables the script to detect added/removed/overridden property for dictionary types in the spec.

Detect changes in json files regarding dictionary types

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/overridingTypes.json

http://www.w3.org/TR/IndexedDB/#database-interface

Update `IDBDatabase` interface

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json

https://github.com/Microsoft/TypeScript/issues/4550

To fix #4550

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json

fix [HTMLPictureElement interface definition is missing
#5323](https://github.com/Microsoft/TypeScript/issues/5323) issue. And add
methods of Document & Element interface which related HTMLPictureElement.

Add HTMLPictureElement Interface

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/addedTypes.json
inputfiles/overridingTypes.json
inputfiles/removedTypes.json

fixes https://github.com/Microsoft/TypeScript/issues/6501
spec https://www.w3.org/TR/IndexedDB/

Update IndexedDB interfaces

---

Shared.fsx
TS.fsx
baselines/dom.generated.d.ts

The issue:
For interfaces marked as `static` in the spec, we used to not detect changes made in the external json files.
Related to PR #44

Detect added json items for static interfaces

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/overridingTypes.json

Fixes https://github.com/Microsoft/TypeScript/issues/6534
[Spec](https://webaudio.github.io/web-audio-api/#BaseAudioContext) here.
The `disconnect` signature is simplified by optional parameter.

Update AudioNode and DecodeErrorCallback to webaudio spec

---

TS.fsx
inputfiles/sample.json

For the `window` interface, we normally expose every property of it to the top level using `declare var`. However in rare cases where the property was added from external source, while it was already declared as a constructor function, so emitting again will cause issues. 
Related: PR #58

Choose to not expose some property for "window" interface

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json

With HTML Imports, <link> elements now have an 'import' property, providing access to the referenced document.
Spec: https://www.w3.org/TR/html-imports/#interface-import
I've left this optional, since it won't exist at all for browsers that don't support HTML Imports yet, and it's always null for browsers that do if the <link> doesn't have `rel='import'`.

Add 'import' to HTMLLinkElements

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json
inputfiles/comments.json

Fixes https://github.com/Microsoft/TypeScript/issues/7197
HTML5 spec:
https://www.w3.org/TR/html5/forms.html#the-maxlength-and-minlength-attributes

Add minLength property to input & textarea

---

Shared.fsx
TS.fsx
inputfiles/sample.json

Help with #66 
Now one can add a base interface to an interface as follows:
```json
{
"kind": "extends",
"baseInterface": "ParentNode",
"interface": "Document"
}
```

Add support for extends

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json
inputfiles/overridingTypes.json

First PR for [Microsoft/TypeScript#424](https://github.com/Microsoft/TypeScript/issues/424)

Update HTMLCollection and Add HTMLCollectionOf<T extends Element>

---

TS.fsx
baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
build.cmd
inputfiles/sample.json

Add "readonly" modifier for property and constants

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json

fix: [#7846](https://github.com/Microsoft/TypeScript/issues/7846)
spec: [CanvasRenderingContext2D.imageSmoothingEnabled](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/imageSmoothingEnabled)

Add CanvasRenderingContext2D.msImageSmoothingEnabled with vender-prefix

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json
inputfiles/overridingTypes.json

PR for [Microsoft/TypeScript#7712](https://github.com/Microsoft/TypeScript/issues/7712)

Add signature overloads for XHTML and SVG namespaces

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.json

According to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Node/insertBefore), the second parameter of insertBefore is not optional (which is was fixed in #95), but it can accept `null`. Under `strictNullChecks` this is currently not allowed, this PR fixes that.

Second parameter of insertBefore should accept null

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/addedTypes.json
inputfiles/overridingTypes.json

This should, among other things, sort of address [TS issue #3984](https://github.com/Microsoft/TypeScript/issues/3984). Fully making the return type a `Promise` instead of a `PromiseLike` is dependent on some sort of resolution of [the ability to target the ES6 library separately](https://github.com/Microsoft/TSJS-lib-generator/issues/47). Reference document used to create these typings is [the 2014.12 W3C WebCrypto API CR](https://www.w3.org/TR/WebCryptoAPI/).
Generally speaking, this should make code work that used to not compile (such as importing JSON web keys). The only *more* restrictive change, I believe, is making the `name` property of `Algorithm` no longer optional. It is explicitly documented as required in the W3C document.

flesh out webcrypto

---

Shared.fsx
TS.fsx
baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts

Correct the event type for event handler properties.
Related to https://github.com/Microsoft/TSJS-lib-generator/pull/106

Fix OnError handlers

---

TS.fsx
baselines/dom.generated.d.ts
inputfiles/addedTypes.json

http://www.w3.org/TR/html5/scripting-1.html#the-canvas-element
```webidl
typedef (CanvasRenderingContext2D or WebGLRenderingContext) RenderingContext;
interface HTMLCanvasElement : HTMLElement {
attribute unsigned long width;
attribute unsigned long height;
RenderingContext? getContext(DOMString contextId, any... arguments);
DOMString toDataURL(optional DOMString type, any... arguments);
void toBlob(FileCallback? _callback, optional DOMString type, any... arguments);
};
```

Add `type` argument on toBlob()

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json
inputfiles/removedTypes.json

According to the MDN (https://developer.mozilla.org/en-US/docs/Web/API/Element), insertAdjacent* methods should be part of the Element interface.
Issue: #130

Moved insertAdjacent* methods from HTMLElement interface to parent

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json

fix [#9698](https://github.com/Microsoft/TypeScript/issues/9698)

Add secureConnectionStart property for PerformanceTiming interface

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json

fix [#8955](https://github.com/Microsoft/TypeScript/issues/8955)

Add integrity property

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/addedTypes.json

If you leave the parameters named typedCurve it compiles clean but when run in the browser (Chrome 51) it fails with the following error Uncaught (in promise) TypeError: EcKeyGenParams: namedCurve: Missing or not a string(…).
If you change it to namedCurve tsc will have an error but the generated code runs without issue. 
This pull request should fix this so that you have clean compilation and error free generated code.

changed EcKeyGenParams from typedCurve to namedCurve to fix issue

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json

This addresses issue [9206](https://github.com/Microsoft/TypeScript/issues/9206) in TypeScript.
It adds the missing code[1][2][3] property to interface KeyboardEvent.
[1] https://www.w3.org/TR/uievents/#keys-codevalues
[2] https://w3c.github.io/uievents/#keys-codevalues
[3] https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code

Added missing property code to interface KeyboardEvent

---

TS.fsx
baselines/dom.generated.d.ts

Fix https://github.com/Microsoft/TypeScript/issues/9850

Make the global var `name` of type `never`

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json

Completing the work of [pull request 136](https://github.com/Microsoft/TSJS-lib-generator/pull/136)
This addresses issue https://github.com/Microsoft/TypeScript/issues/9206 in TypeScript.
It adds the missing code[1][2][3] property to interface KeyboardEventInit.
[1] https://www.w3.org/TR/uievents/#keys-codevalues
[2] https://w3c.github.io/uievents/#keys-codevalues
[3] https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code

Added missing property code to interface KeyboardEventInit

---

TS.fsx
baselines/dom.generated.d.ts
inputfiles/addedTypes.json
inputfiles/sample.json

fix [#4400](https://github.com/Microsoft/TypeScript/issues/4400), [#7528](https://github.com/Microsoft/TypeScript/issues/7528)

Add ParentNode interface

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.json

fix [2.0: window.opener declared as readonly #10379](https://github.com/Microsoft/TypeScript/issues/10379)
I follow [w3c spec](https://w3c.github.io/html/browsers.html#the-window-object)

fix window.opener property

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json
inputfiles/overridingTypes.json

Fixes https://github.com/Microsoft/TypeScript/issues/10059

Fix the History api

---

baselines/dom.generated.d.ts
inputfiles/removedTypes.json

This allows string indexing to be preferred which is the typical expectation for the window object.  Fixes TypeScript issue #10457

Remove number indexer declaration on window object.

---

TS.fsx
baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/overridingTypes.json

fix [#10979](https://github.com/Microsoft/TypeScript/issues/10979)

change DataTransfer.types property from DOMStringList to string[]

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.json

to resolve https://github.com/Microsoft/TypeScript/issues/11583

Override window.event type

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.json

This should fix https://github.com/Microsoft/TypeScript/issues/11981 
I've also changed the return type of `XPathExpression.evaluate` to `XPathResult` based on https://developer.mozilla.org/en-US/docs/Web/API/XPathExpression

evaluate should allow null for resolver and result

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/addedTypes.json
inputfiles/overridingTypes.json

Based on https://www.w3.org/TR/2016/WD-shadow-dom-20160830/

Add Shadow DOM v1 APIs

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json

Source: https://www.w3.org/TR/2016/WD-custom-elements-20160830/
As suggested by comments on https://github.com/Polymer/polymer/pull/3954

Add typings for custom elements v1 API

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/addedTypes.json
inputfiles/overridingTypes.json

According to the spec
https://html.spec.whatwg.org/multipage/webappapis.html#the-errorevent-interface
ErrorEvent constructor accept some params
This fixes https://github.com/Microsoft/TypeScript/issues/12644

Correct signature of ErrorEvent constructor

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json

Build was broken because `Element` inherits from both `ElementTraversal` and `ParentNode`, while a recent PR made two properties from `ElementTraversal` nullable, so TS complains these properties have different types in different base types. 
Related spec:
https://dom.spec.whatwg.org/#dom-parentnode-firstelementchild
The `firstElementChild` and `lastElementChild` are indeed nuallble as well in `ParentNode` interface.

Fix build error

---

README.md

Not sure what exact standards should be used. Hopefully someone more familiar with web standards can comment.
This will affect whether we choose #176 or DefinitelyTyped/DefinitelyTyped#13045.

Add guidelines for when a DOM API belongs here vs on DefinitelyTyped

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.json

Fixes: https://github.com/Microsoft/TypeScript/issues/13792
Currently, the DOMStringMap interface doesn't respect that elements in the map may be undefined. This makes it easy to result in type errors around its usage.
This PR adds a union with the `undefined` type to the elements in order to accurately reflect its possible runtime types.

Fix lack of undefined for DOMStringMap indexer

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json

https://github.com/Microsoft/TypeScript/issues/10297

add PromiseRejectionEvent from WHATWG Living Standard

---

TS.fsx
baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts

Fix for https://github.com/Microsoft/TypeScript/issues/13947
Blocked on https://github.com/Microsoft/TypeScript/pull/14053

Use Promise<T> instead of PromiseLike<T>

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.json

Suggested fix for issue [#14305](https://github.com/Microsoft/TypeScript/issues/14305)

Fix 14305: Set texImage2D and texSubImage2D last parameter non-optional

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.json

According to the [DOM Specification](https://www.w3.org/TR/DOM-Level-2-Core/core.html#ID-102161490) the `doctype` parameter can be null.
Fixes Microsoft/TypeScript#14229

Fix DOMImplementation.createDocument signature

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.json

See [spec](https://webaudio.github.io/web-audio-api/#widl-AudioNode-connect-void-AudioParam-destination-unsigned-long-output)
Fixes Microsoft/TypeScript#14355

Fix AudioNode.connect method

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/addedTypes.json

Fixes [ImageBitmap interface missing #14402](https://github.com/Microsoft/TypeScript/issues/14402)
Adds interfaces `ImageBitmap`, `ImageBitmapOptions` and the associated typedefs to Window and Worker scope. See [WHATWG HTML Living Standard](https://html.spec.whatwg.org/multipage/webappapis.html#imagebitmap)
Wasn't sure about the "flavor" tag. `Worker` seems to be the one I need here. but is there a description of `All`, `Web`, `DOM` and maybe others?

Added ImageBitmap interface

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.json

Suggested fix for [#14592](https://github.com/Microsoft/TypeScript/issues/14592).
* provides correct parameter names for all three overloads
* forces correct number of parameters (3, 5 or 9)
* adds `ImageBitmap` as possible image source (see #210)

Split CanvasRenderingContext2D.drawImage signature

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.json

Just a small follow-up on PR #210 (Added ImageBitmap interface):
This PR also adds `ImageBitmap` as possible source for WebGL's `texImage2D` and `texSubImage2D`.
MDN Link: https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/texImage2D

Added ImageBitmap as texImage2D source

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json

Fix for Microsoft/TypeScript#14795
Adds method DataTransfer.setDragImage

Fixes Microsoft/TypeScript#14795

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/addedTypes.json
inputfiles/overridingTypes.json

Fixes https://github.com/Microsoft/TypeScript/issues/14813 by updating the existing append method to better match the [Web APIs](https://developer.mozilla.org/en-US/docs/Web/API/FormData/FormData) and adding missing methods. Please let me know if there is anything I should add or change, thanks!

Add missing methods for FormData type

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/addedTypes.json
inputfiles/knownWorkerInterfaces.json

`URL` is also available in worker. ([URL IDL spec](https://url.spec.whatwg.org/#idl-index)). Fix https://github.com/Microsoft/TypeScript/issues/14878.
---
**Questions**:
1. `URL` tying is already defined in [`inputfiles/browser.webidl.xml#L11367-L11395`](https://github.com/Microsoft/TSJS-lib-generator/blob/master/inputfiles/browser.webidl.xml#L11367-L11395), so it is only need to added to `worker`. So I added `"flavor": "Worker"`, but it seems doesn't work.(same as `"flavor": "All"` for `URLSearchParams`) 😅
2. I'm not sure whether the `URL` and `URLSearchParams` should be added to `WorkerGlobalScope`.  It is signed as `Exposed=(Window,Worker)` in the [spec IDL](https://url.spec.whatwg.org/#idl-index)
3. The spec IDL use `USVString`, but I use `string` here (keep it same as previous added …

add URL typing to webworker

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.json

Fixes https://github.com/Microsoft/TypeScript/issues/14863

Improve method signatures returning Node type

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/addedTypes.json
inputfiles/overridingTypes.json

According to https://dom.spec.whatwg.org/#interface-eventtarget
* The `EventTarget.addEventListener` `useCapture` argument must be (AddEventListenerOptions or boolean)
* The `EventTarget.removeEventListener` `useCapture` argument must be (EventListenerOptions or boolean)
Fix issue https://github.com/Microsoft/TypeScript/issues/14188

Fix the EventTarget.addEventListener and EventTarget.removeEventListener useCapture argument - related to issue #14188

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.json

Add missing optional constructor param for Text

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.json

Closes issue #15691
https://github.com/Microsoft/TypeScript/issues/15691
* Previously the return type was void
* According to https://html.spec.whatwg.org/multipage/embedded-content.html#dom-media-play it should be Promise<void>

Updated HTMLMediaElement.play return type to Promise<void>

---

TS.fsx
baselines/webworker.generated.d.ts
inputfiles/knownWorkerInterfaces.json
inputfiles/overridingTypes.json

`FormData` is also available in worker. ([IDL spec](https://xhr.spec.whatwg.org/#interface-formdata)). 
The `FormData` declaration in DOM is
```ts
declare var FormData: {
prototype: FormData;
new (form?: HTMLFormElement): FormData;
}
```
But `HTMLFormElement` is not available in worker. So I think we should change the constructor to:
(but can't find related info in [w3c spec](https://xhr.spec.whatwg.org/#interface-formdata))
```ts
new (): FormData;
```
I add a `flavor` to `inputfiles/overridingTypes.json`, but it seems not work. How can I achieve this？

add FormData typing to webworker

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json

`navigator.languages` is currently not being provided along with the DOM type definitions, this PR adds it.
From the HTML 5.1 W3Cw spec:
> `window.navigator.languages`
>     Returns an array of language tags representing the user’s preferred languages, with the most preferred language first. The most preferred language is the one returned by navigator.language. 
https://www.w3.org/TR/2016/REC-html51-20161101/webappapis.html#language-preferences
TypeScript issue:
https://github.com/Microsoft/TypeScript/issues/16246

Add navigator.languages

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json

Copy-pasted from issue #257:
ValidityState is missing tooShort:
```ts
interface ValidityState {
readonly badInput: boolean;
readonly customError: boolean;
readonly patternMismatch: boolean;
readonly rangeOverflow: boolean;
readonly rangeUnderflow: boolean;
readonly stepMismatch: boolean;
readonly tooLong: boolean;
// missing => readonly tooShort: boolean;
readonly typeMismatch: boolean;
readonly valid: boolean;
readonly valueMissing: boolean;
}
```
See https://github.com/Microsoft/TSJS-lib-generator/blob/475f27eacbec630695df8ae7b38ebeff2926b92f/baselines/dom.generated.d.ts#L11872
See MDN doc: https://developer.mozilla.org/en-US/docs/Web/API/ValidityState
See HTML 5.0 spec: https://www.w3.org/TR/html5/forms.html#validitystate
See HTML 5.2 spec (draft): …

Add tooShort to ValidityState

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.json

to `Int8Array | Uint8ClampedArray | Uint8Array | Int16Array | Uint16Array | Int32Array | Uint32Array`, persuant to [the latest reccomendation](https://www.w3.org/TR/WebCryptoAPI/#Crypto-method-getRandomValues).

Restrict the views accepted by crypto.getRandomValues

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/addedTypes.json

FilePropertyBag should extends BlobPropertyBag according to standard: https://github.com/Microsoft/TypeScript/issues/16400

fix FilePropertyBag should extends BlobPropertyBag according to standard

---

TS.fsx
baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts

This adds support for the `required` and `nullable` keys when they are specified in IDL dictionaries. Currently, any modifiers are ignored.
There is also a `default` key often present in dictionary keys, but those look like they would only be useful, TypeScript-wise, for documentation.
This is likely a breaking change... but code that would break with this was already incorrect, as IDL specifies those keys as required.

Add support for required and nullable to IDL dictionaries

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/overridingTypes.json

Fixes https://github.com/Microsoft/TypeScript/issues/15101
This will change the type of `this` inside the functions for
* `onload`
* `onloadstart`
* `onloadend`
* `onabort`
* `onprogress`
* `ontimeout`
* `onerror`
in both `XMLHttpRequest` and `XMLHttpRequestUpload`.

fix: Type of `this` for XMLHttpRequest properties

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.json

Fixes [#16543](https://github.com/Microsoft/TypeScript/issues/16543) by updating the form property of form associated elements a nullable type to better match the [spec](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#association-of-controls-and-forms) - which specifies that:
> if a form-associated element is not associated with a form element its form owner is said to be null.
Please let me know if there is anything I should update or change. Thanks!

Make form property of form associated elements a nullable type

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/addedTypes.json

Fixes https://github.com/Microsoft/TypeScript/issues/15407
I cannot add the following code. How can I do that?
```ts
declare var BroadcastChannel: {
prototype: BroadcastChannel;
new(name: string): BroadcastChannel;
}
```

Add BroadcastChannel API

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json

Fixes https://github.com/Microsoft/TypeScript/issues/17872
All 3 elements are living standards

Added HTML main, details, and summary elements

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/overridingTypes.json

From https://fetch.spec.whatwg.org/#headers-class
> typedef (sequence<sequence<ByteString>> or record<ByteString, ByteString>) HeadersInit;
it also can be a `Headers` object. which is a bit redundant.

Fix https://github.com/Microsoft/TypeScript/issues/18073

---

README.md
baselines/dom.generated.d.ts
inputfiles/overridingTypes.json

Update return type signature of `window.open` from `Window` to `Window | null`. Solves [Microsoft/TypeScript/#18132](https://github.com/Microsoft/TypeScript/issues/18132#issuecomment-327313732).
Also, I made a slight change to the common PR steps section of README - I thought being more explicit could help a very beginner (like myself).

Change return type of window.open to Window | null (#18132)

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json

As seen on https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#dom-cva-reportvalidity and https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/reportValidity 
I hope I did everything correctly!
Fixes https://github.com/Microsoft/TypeScript/issues/18733

add HTMLFormElement.reportValidity

---

TS.fsx
baselines/dom.generated.d.ts

Fixes https://github.com/Microsoft/TypeScript/issues/18891 by avoiding emitting usage DOM event handlers. Unsafe handlers are ones that are defined in a parent with arguments with less specialized types.

Fix https://github.com/Microsoft/TypeScript/issues/18891: Do not emit unsafe event handlers

---

TS.fsx
baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts

These overload signatures are primarily there to suppress errors when strictFunctionTypes is enabled.
https://github.com/Microsoft/TypeScript/issues/19386

Generate typed signatures for removeEventListenter

---

TS.fsx
baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/addedTypes.json

For the signatures generated within TS.fsx:
* Changes the type of the third argument to `boolean | AddEventListenerOptions` for `addEventListener`
* Changes the type of the third argument to `boolean | EventListenerOptions` for `removeEventListener`
Additionally, there were a few changes in addedTypes.json that needed to be updated by adding `removeEventListener` signatures and updating both `addEventListener` and `removeEventListener` to allow for `AddEventListenerOptions`/`EventListenerOptions`:
* BroadcastChannel
* IDBDatabase (additionally I added `this: IDBDatabase` for the 'versionchange' signatures)
Addresses:  
https://github.com/Microsoft/TypeScript/issues/18136

adding [Add]EventListenerOptions parameter for generated signatures

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.json

This addresses TypeScript issue https://github.com/Microsoft/TypeScript/issues/19200. As per https://www.w3.org/TR/payment-request/#paymentmethoddata-dictionary, supportedMethods was changed from an array to a string, but the name was left plural.

fix #19200 PaymentMethodData.supportedMethods

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json

This pull request will allow the Element `closest` method to infer the HTML Element type rather than returning a generic Element.

Add generic type to closest method of Element.

---

TS.fsx
baselines/dom.generated.d.ts
inputfiles/overridingTypes.json
inputfiles/sample.json

This PR will fix https://github.com/Microsoft/TypeScript/issues/14785 and replace https://github.com/Microsoft/TSJS-lib-generator/pull/304.
In order to override interfaces and add types this PR updates the TS.fsx and adds a new override type called `typedinterface`.  The naming convention was provided here https://github.com/Microsoft/TSJS-lib-generator/pull/304#issuecomment-341561311
This is my first time writing F# so please let me know if I need to make changes to the convention or if I missed an interfaces beyond Dictionaries or Interface Declarations.

Add overrides for interface types and add CustomEvent types for testing.

---

TS.fsx
baselines/dom.generated.d.ts
inputfiles/addedTypes.json

Fixes https://github.com/Microsoft/TypeScript/issues/20149, https://github.com/Microsoft/TypeScript/issues/20134

Remove ElementTagNameMap

---

TS.fsx
baselines/dom.generated.d.ts
inputfiles/addedTypes.json

https://github.com/Microsoft/TSJS-lib-generator/pull/326 removed `ElementTagNameMap`. turns our types in [Definitelytyped depended on it](https://github.com/DefinitelyTyped/DefinitelyTyped/search?utf8=%E2%9C%93&q=ElementTagNameMap&type=). Putting it back.

Add back element tag name map

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json

As reported in TypeScript issue #20756:
https://github.com/Microsoft/TypeScript/issues/20756
Spec here:
https://html.spec.whatwg.org/multipage/iframe-embed-object.html#attr-object-typemustmatch

Add typemustmatch property on <object>

---

baselines/dom.generated.d.ts
inputfiles/comments.json
inputfiles/overridingTypes.json

Fixes https://github.com/Microsoft/TypeScript/issues/20419.
The `start` and `end` parameters of the [`HTMLInputElement.setSelectionRange()`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/setSelectionRange) API are _not_ optional.
In addition, the `direction` parameter only accepts one of three string values, which is why it's now typed using string literal types.

Fix type declarations for "setSelectionRange" API

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/addedTypes.json

Reported in Microsoft/TypeScript#19418
Specs:
- https://dom.spec.whatwg.org/#aborting-ongoing-activities
- https://fetch.spec.whatwg.org/#dom-requestinit-signal

Add abortable fetch interfaces

---

TS.fsx

This removes F# lint errors by:
1. deleting unused functions/constants
2. replacing unused identifiers to `_` or `__` (where `_` is not applicable)
3. using linter-suggested simpler code

Code cleanup

---

TS.fsx
baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/addedTypes.json
inputfiles/overridingTypes.json

Fixes #351.
Callback interfaces including WebKitEntriesCallback have incorrect signatures so this fixes them.
IMO the WebKit-specific types should ultimately excluded, but anyway this change will help future WebIDL works. (NodeFilter is a callback interface by standard specification)

Fix callback interfaces

---

baselines/dom.generated.d.ts
inputfiles/comments.json
inputfiles/removedTypes.json

alt is not part of the HTML Standard for HTMLObjectElement
Fixes Microsoft/TypeScript#21386

Remove alt attribute from HTMLObjectElement interface

---

TS.fsx
baselines/dom.generated.d.ts
inputfiles/addedTypes.json
inputfiles/sample.json

Fixing Microsoft/TypeScript#21669
See diff without whitespace changes [here](https://github.com/Microsoft/TSJS-lib-generator/compare/master...e111077:master?w=1).
Possible controversial topics in this PR:
1. I modified `inputfiles/sample.json` to include an HTML element with a `tagNames` field.
2. I added a `tagNames` field to `inputfiles/addedTypes.json`'s `HTMLSlotElement`
1. I figured this was the correct-most way to find associations between tag names and interfaces
2. It causes duplication of the `slot` property. See [here](https://github.com/e111077/TSJS-lib-generator/blob/3f8d2427b24442d071b2a684ed21f168c03a6861/inputfiles/addedTypes.json#L1541).
3. I added the "addedTypes" to `iNameToIDependList `'s `getExtendList` but not the `getImplementList`
1. It was required to get through …

HTML Elements in addedTypes.json are mapped tagName -> Interface

---

TS.fsx
baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/addedTypes.json
inputfiles/overridingTypes.json

https://github.com/Microsoft/TSJS-lib-generator/pull/352 introduced a few issues, this PR addresses them.
Fix Microsoft/TypeScript#21948
Fix Microsoft/TypeScript#21922
Supersedes https://github.com/Microsoft/TSJS-lib-generator/pull/374

Fix few issues with EventListener and EventListenerOrEventObject

---

TS.fsx
baselines/dom.generated.d.ts
inputfiles/addedTypes.json

Fixes https://github.com/Microsoft/TypeScript/issues/21822

Add focusin, focusout events to DocumentEventMap/HTMLElementEventMap

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json
inputfiles/comments.json

According to MDN: https://developer.mozilla.org/en-US/docs/Web/API/HTMLAnchorElement
https://github.com/Microsoft/TypeScript/issues/21943

Update HTMLAnchorElement: added origin property

---

TS.fsx
baselines/dom.es6.generated.d.ts
baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts

In preparation for some refactoring of the generation script, this change reorders the declarations by name to make it more amenable to comparison.

Sort declarations

---

src/types.d.ts

I've found creating some `WebIdl` types by TypeScript can be painful because of the added `"override-type"?: string;` on `Typed`.
```ts
import * as webidl2 from "webidl2"
import * as Browser from "./types";
function convertIdlType(t: webidl2.IDLTypeDescription): Browser.Typed { /* ... */ }
function convertParam(t: webidl2.Argument): Browser.Param {
return {
/*
* ... some Param specific properties ...
*/
...convertIdlType(t.idlType) // Error: override-type does not exist in Browser.Param
}
}
```
Those types really just extend Typed, so this PR uses `extends Typed` syntax to allow the destructuring work.

Use `extends Typed` for the appropriate types from type.d.ts

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json

- [WHATWG](https://dom.spec.whatwg.org/#dom-domtokenlist-replace)
- [MDN](https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/replace)
Fixes Microsoft/Typescript#22466
Related: Microsoft/Typescript#22475

Add DOMTokenList.replace()

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json

[WHATWG/attr-img-decoding](https://html.spec.whatwg.org/#attr-img-decoding)
> The decoding attribute indicates the preferred method to decode this image. The attribute, if present, must be an image decoding hint. This attribute's missing value default and invalid value default are both the auto state.
Closes #392

Add HTMLImageElement.decoding

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json
package.json

I'm not entirely sure what I'm doing, but if I've done this right it fixes https://github.com/Microsoft/TypeScript/issues/22565 - a regression created in https://github.com/Microsoft/TSJS-lib-generator/pull/383#issuecomment-376132738.

Adding touch event typings

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/addedTypes.json
inputfiles/knownWorkerTypes.json
inputfiles/overridingTypes.json

This PR fixes https://github.com/Microsoft/TypeScript/issues/4163.
The [FileReader API spec](https://www.w3.org/TR/FileAPI/#events) says the event target is `FileReader` so I give `FileReader` type to `target` of `ev`.

Add type to FileReader event target.

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.json

[Microsoft/TypeScript#/22673](https://github.com/Microsoft/TypeScript/issues/22673)

Add missing message property to MediaError

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json
src/preprocess.ts

Fixes https://github.com/Microsoft/TypeScript/issues/23149

Add `onbeforreprint` and `onafterprint` events to `Window`

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/addedTypes.json
inputfiles/idl/Fetch.widl
inputfiles/idlSources.json
inputfiles/knownWorkerTypes.json
inputfiles/removedTypes.json
src/emitter.ts
src/index.ts
src/types.d.ts
src/widlprocess.ts

Adds Response.trailer, fixes BodyInit, etc.

Add Fetch standard types

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.json

[TSJS-lib-generator#423](https://github.com/Microsoft/TSJS-lib-generator/issues/423)
[whatwg#relList](https://html.spec.whatwg.org/multipage/text-level-semantics.html#dom-a-rellist)

Add relList to HTMLAnchorElement, HTMLAreaElement, HTMLLinkElement

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/addedTypes.json
inputfiles/knownWorkerTypes.json
inputfiles/overridingTypes.json

Fixes #426, closes #427 
IDBValidKey and IDBArrayKey is not defined in IDL, so this PR manually updates and uses them as [the spec says](https://www.w3.org/TR/IndexedDB-2/#key-construct):
>The following ECMAScript types are valid keys:
>
>* Number primitive values, except NaN. This includes Infinity and -Infinity.
>* Date objects, except where the [[DateValue]] internal slot is NaN.
>* String primitive values.
>* ArrayBuffer objects (or views on buffers such as Uint8Array).
>* Array objects, where every item is defined, is itself a valid key, and does not directly or indirectly contain itself. This includes empty arrays. Arrays can contain other arrays.
>
>Attempting to convert other ECMAScript values to a key will fail.

Update/use IDBValidKey

---

baselines/dom.generated.d.ts
inputfiles/idl/WebRTC.widl

This creates RTCRtpSendParameters which splits and extends from old RTCRtpParameters.

Reflect WebRTC change

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/idl/Push.widl
inputfiles/idl/Web Background Synchronization.widl
inputfiles/idlSources.json
inputfiles/knownWorkerTypes.json

Add push/sync types

---

baselines/dom.generated.d.ts
inputfiles/removedTypes.json
src/emitter.ts
src/index.ts
src/types.d.ts
src/widlprocess.ts

[Geometry Interfaces Module](https://drafts.fxtf.org/geometry/) (#421) defines older SVGMatrix, WebKitCSSMatrix, etc. as legacy aliases of DOM-prefixed interfaces by `[LegacyWindowAlias]`.
This PR reads it and emits corresponding aliases, and then removes older type definitions.

Support LegacyWindowAlias

---

baselines/dom.generated.d.ts
baselines/dom.iterable.generated.d.ts
inputfiles/addedTypes.json
inputfiles/overridingTypes.json
src/emitter.ts

...and only keep `[Symbol.iterator](): IterableIterator<T>`.

Remove redundant iterator methods from HTMLCollectionOf

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json
inputfiles/idl/Screen Orientation.widl
inputfiles/idlSources.json
inputfiles/removedTypes.json

Fixes Microsoft/TypeScript#18480

Add Screen Orientation types

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.json

This PR fixes https://github.com/Microsoft/TypeScript/issues/24119.
It removes the `@deprecated` from `disabled` in `HTMLLinkElement`.
Thanks for considering this request.

Fixed #24119 - Removed @deprecated for disabled in HTMLLinkElement

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/addedTypes.json
inputfiles/overridingTypes.json
inputfiles/removedTypes.json
src/emitter.ts
src/expose.ts
src/helpers.ts
src/index.ts

Replaces related lines from #459 
Now non-Worker exposed types are not processed as `"object"` but 1) are omitted if optional 2) throws if not.
This removes some Worker-incompatible non-standard types.

Add exposure module

---

baselines/dom.generated.d.ts
inputfiles/idl/Compatibility.widl
inputfiles/idlSources.json

This just adds `@deprecated`, though.

Add Compatibility types

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json
inputfiles/comments.json
inputfiles/idl/HTML - Grouping content.widl
inputfiles/idlSources.json
src/emitter.ts
src/types.d.ts
tsconfig.json

Adds a deprecated signature of `createElement`.

Add HTML grouping content types

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.json

This PR addresses this issue: https://github.com/Microsoft/TypeScript/issues/19548.
It adds `@deprecated` to `className` in `SVGElement`.
Thanks for considering this PR.

Fixed #19548 - Added @deprecated to className in SVGElement

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json
inputfiles/comments.json
inputfiles/idl/HTML - Semantics.commentmap.json
inputfiles/idl/HTML - Semantics.widl
inputfiles/idlSources.json
inputfiles/overridingTypes.json

Removes `HTMLLinkElement.import`. It was for HTML Imports but the spec hasn't been able to gather enough interest from vendors.

Add HTML semantics types

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json
inputfiles/idl/CSSOM View.widl
inputfiles/idl/Encoding.widl
inputfiles/idl/Fetch.widl
inputfiles/idl/Web IDL.widl
inputfiles/idl/XMLHttpRequest.widl
inputfiles/idlSources.json
src/fetcher.ts

Excluding geometry types marked as `atrisk`. (They have never been implemented by stable browsers.)

Add CSSOM View types

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json

Adds proposed function signature overload.

Proposed fix for issue 501

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.json

This PR addresses https://github.com/Microsoft/TypeScript/issues/24084.
I changed the `HTMLSelectElement` index to `[name: string]: HTMLOptionElement | HTMLOptGroupElement`.
Thanks for considering this PR.

Fixed #24084 - Changed HTMLSelectElement Index Signature

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/addedTypes.json
inputfiles/idl/HTML - Web application APIs.commentmap.json
inputfiles/idl/HTML - Web application APIs.widl
inputfiles/idlSources.json
inputfiles/overridingTypes.json
inputfiles/removedTypes.json
src/emitter.ts
src/widlprocess.ts

Almost all event handlers are moved into GlobalEventHandlers mixin.

Add HTML webappapi types

---

baselines/dom.generated.d.ts
baselines/dom.iterable.generated.d.ts
inputfiles/addedTypes.json
inputfiles/idl/Web Speech API.widl
inputfiles/idlSources.json

Removes SpeechSynthesisEvent constructor as it's not in the spec and it throws on Chrome.

Add Web Speech types

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/addedTypes.json
inputfiles/comments.json
inputfiles/idl/HTML - DOM.commentmap.json
inputfiles/idl/HTML - DOM.widl
inputfiles/idlSources.json
inputfiles/knownTypes.json
inputfiles/overridingTypes.json
inputfiles/removedTypes.json
src/emitter.ts
src/helpers.ts

Diffs are mainly because of HTMLElement not including event handlers anymore.

Add HTML DOM types

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.json

[The spec](https://dom.spec.whatwg.org/#dom-domimplementation-hasfeature) says it's now useless and always returns `true` for web compatilibity.
The IDL specifies zero arguments but here we intentionally want to allow arbitrary arguments to not break backward compatibility. (Web IDL implicitly allows excessive arguments, anyway.)

Mark document.implementation.hasFeature as deprecated

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/overridingTypes.json

[`TypeScript/25509`](https://github.com/Microsoft/TypeScript/issues/25509)

First argument to fetch is optional, but fetch requires at least 1 arg

---

baselines/dom.generated.d.ts
baselines/dom.iterable.generated.d.ts
inputfiles/idl/SVG - Basic Data Types and Interfaces.widl
inputfiles/idl/Screen Orientation.widl
inputfiles/idl/User Timing.widl
inputfiles/idlSources.json
inputfiles/removedTypes.json

Add SVG basic types

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/removedTypes.json
src/emitter.ts
src/index.ts

Fixes #531  
This doesn't look very ideal as this basically copies everything, but not sure what should be done for those inline type literals.
Maybe we can introduce new `(InterfaceName)Constants` interfaces and use them:
```ts
declare var MyClass: {
prototype: MyClass;
new(): MyClass;
} & MyClassConstants;
```
What do you think? @mhegazy

Inherit const members in constructors

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/addedTypes.json
inputfiles/knownTypes.json
inputfiles/overridingTypes.json

This PR addresses https://github.com/Microsoft/TypeScript/issues/25176
Relevant MDN pages:
https://developer.mozilla.org/en-US/docs/Web/API/BroadcastChannel/postMessage
https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage
https://developer.mozilla.org/en-US/docs/Web/API/Client/postMessage
https://developer.mozilla.org/en-US/docs/Web/API/Worker/postMessage
https://developer.mozilla.org/en-US/docs/Web/API/MessagePort/postMessage
https://developer.mozilla.org/en-US/docs/Web/API/DedicatedWorkerGlobalScope/postMessage
Map and Set do not seem to be available in `dom.generated.d.ts`. How would one implement the `Messageable` type?

Introduce Messageable and Transferable for postMessage

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json

Specification:
https://html.spec.whatwg.org/multipage/webappapis.html#unhandled-promise-rejections
> Let _notHandled_ be the result of [firing an event](https://dom.spec.whatwg.org/#concept-event-fire) named [`unhandledrejection`](https://html.spec.whatwg.org/multipage/indices.html#event-unhandledrejection) at settings object's [global object](https://html.spec.whatwg.org/multipage/webappapis.html#concept-settings-object-global), using [`PromiseRejectionEvent`](https://html.spec.whatwg.org/multipage/webappapis.html#promiserejectionevent), …

Type unhandledrejection event of WindowEventHandlers

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json
inputfiles/idl/DOM Parsing and Serialization.widl
inputfiles/idlSources.json
package-lock.json
package.json
src/fetcher.ts

This is the cause of the CI failure. Temporarily rolling back to TS 2.9.2.
Closes #555

Add DOM Parsing and Serialization types

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/comments.json
inputfiles/idl/Fullscreen.commentmap.json
inputfiles/idl/Fullscreen.widl
inputfiles/idl/HTML - Web application APIs.widl
inputfiles/idlSources.json
inputfiles/overridingTypes.json

Fixes #551 
The original types from MSEdge was accidentally removed by #523.

Add Fullscreen types

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/addedTypes.json
inputfiles/knownTypes.json
inputfiles/overridingTypes.json
inputfiles/removedTypes.json
src/emitter.ts

Fixes a set of issues that were identified by our real world code test suits.

Fix lib breaks

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.json

According to the issue discussed in https://github.com/Microsoft/TypeScript/issues/26437 `XPathNSResolver`'s property `lookupNamespaceURI` should also return `null` and `Document`'s `evaluate` method should accept  _"a function which returns a String and takes a String parameter instead of the resolver parameter."_ (and also return `null` if needed).
I had originally created the PR in https://github.com/Microsoft/TypeScript/pull/27592, my bad, this is the correct place to change.

Override XPathNSResolver and document's evaluate method

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.json

Fixes an issue similar to #558.
Discovered in `puppeteer` on DefinitelyTyped.

Make Document#documentElement non-null

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/idl/HTML - Canvas.widl
inputfiles/idl/HTML - DOM.widl
inputfiles/idl/HTML - Form elements.widl
inputfiles/idl/Web Animations.widl
inputfiles/idl/WebRTC.widl
inputfiles/knownTypes.json
inputfiles/overridingTypes.json
src/emitter.ts
src/types.d.ts

This is an initial attempt at fixing https://github.com/Microsoft/TypeScript/issues/26073
It should possibly be split up into several patches/PRs but I wanted to get some initial feedback first.
A few notes:
* I've included the update to the `CompositeOperationOrAuto` type which was [recent spec change](https://github.com/w3c/csswg-drafts/commit/ced6b5aac02e0e021001f10e4d63e03456686dad), simply because it makes the index type for `PropertyIndexedKeyframes` a little more sane.
* I have no idea how to represent this sort of open dictionary with a few typed keys in TypeScript so this approach might be completely wrong. Bear in mind that with the arrival of animatable custom properties the set of properties that can be specified on a keyframe is essentially open-ended.
* Allowing `number` for …

Update Web Animations keyframe definitions

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/idl/File.widl
inputfiles/idlSources.json

Change from `label` to the more descriptive `encoding` ([MDN docs][1]).
[1]: https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsText
Fixes Microsoft/TypeScript#25797

Change FileReader.readAsText‘s 2nd argument name

---

baselines/dom.generated.d.ts
inputfiles/removedTypes.json

Microsoft/TypeScript#27886
These fields originated from the deprecated [MouseWheelEvent](https://developer.mozilla.org/en-US/docs/Web/API/MouseWheelEvent) type, which is currently defined as `type MouseWheelEvent = WheelEvent;`.
I couldn't find any references to this type so it might make sense to remove it, since it already is incorrect and will be broken even more through this fix.
`onmousewheel: ((this: Window, ev: Event) => any) | null;`
The corresponding listeners simply use `Event`.
If there is any reason to keep MouseEventWheel, I think creating an extra interface for it would be the best solution. Feedback is welcome.

Remove wheelDelta fields from WheelEvent

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.json

Discovered in `match-media-mock` on DefinitelyTyped.

Ensure MediaQueryList#removeListener matches addListener

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json

Hi, first time contributor, so beware.
Trying to add the missing "referrerPolicy" attribute to iframe:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-referrerpolicy
Would like to check a few things:
- Can someone confirm referrerPolicy should be "readonly"? I'm not 100% sure how to determine this, following the "sandbox" example.
- string or ReferrerPolicy type? (In other use-cases, referrerPolicy is mostly defined as "string" whereas there is one example usage of type ReferrerPolicy. The type has the correct values though)
- Should I open a bug on main TS repository referencing this, or is this fine as such?
Thanks.

add referrerPolicy to HTMLIFrameElement

---

inputfiles/idlSources.json

It was once in WebRTC repo but is later separated.

Relocate Identity for WebRTC spec

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json

This adds `caretRangeFromPoint` and `caretPositionFromPoint` to `DocumentOrShadowDOM` in `dom.generated.d.ts`.
I tried to remove them from `Document` as well, since that inherits from `DocumentOrShadowDOM`, but doing that caused all kinds of changes to the generated code that I couldn't explain, so I didn't feel qualified to touch that and left the existing properties on the `Document` class.
Issue https://github.com/Microsoft/TypeScript/issues/28155#issuecomment-433487385

Add caret(Range/Position)FromPoint to DocumentOrShadowDOM

---

src/fetcher.ts

`npm run fetch` takes too much time to debug or causes too much changes to create a single PR, as it always fetches every registered spec.
This PR allows `npm run fetch -- (specTitle1) (specTitle2), (...)` so that contributors can open a PR more easily.

Allow fetching each spec

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/overridingTypes.json

This PR changes `Event.srcElement` type to `EventTarget` and exposes it to Worker. Accepting this PR should close https://github.com/Microsoft/TypeScript/issues/28252, however I would like to hear from @mhegazy first as to why `Element` type was chosen. Maybe there's a specific reason I don't know and now I'm ruining everything :).

Change `Event.srcElement` type to `EventTarget` and expose it to Worker

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/addedTypes.json

For some reason AbortSignal has event type of `ProgressEvent`, however I could not find anywhere, where it specifies that it must have `ProgressEvent` interface (might have been a copy-paste typo in https://github.com/Microsoft/TSJS-lib-generator/pull/523/commits/260bdbdcd279c2e89dc7d9be938ef03abcfa28c2). Therefore it it should have `Event` interface for `abort` event.
`ProgressEvent` could lead to errors: [proof (kinda)](http://jsfiddle.net/y5gacx3o/1/).

Change AbortSignal's event type to Event

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json
inputfiles/comments.json

DocumentOrShadowRoot needs to be a mixin, not an interface,
to allow us to extend it without addedTypes.json overwriting it.
Fixes issue #551

Fix DocumentOrShadowRoot.fullscreenElement

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.json

As discussed in https://github.com/Microsoft/TypeScript/issues/28551 a Node's `nextSibling` should have type of `ChildNode` so types can match when comparing or assigning elements.
I've noticed also `nextSibling` present in the interface `MutationRecord` [here](https://github.com/Microsoft/TSJS-lib-generator/blob/master/baselines/dom.generated.d.ts#L10225) and in the interface `TreeWalker` as a method [here](https://github.com/Microsoft/TSJS-lib-generator/blob/master/baselines/dom.generated.d.ts#L15023).
Not sure about those other two occurrences, but at least it seems consistent the change in `Node`. Let me know if you guys have any comment!
Cheers!

Override Node nextSibling to be type of ChildNode.

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.json

[Per the spec](https://dom.spec.whatwg.org/#ref-for-dom-window-event):
>Web developers are strongly encouraged to instead rely on the `Event` object passed to event listeners, as that will result in more portable code. This attribute is not available in workers or worklets, and is inaccurate for events dispatched in shadow trees.

Mark window.event as deprecated

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.json

Fixes https://github.com/Microsoft/TypeScript/issues/28638

Fix ErrorEventHandler.error signature to `error?: any`.

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.json

Addresses https://github.com/Microsoft/TypeScript/issues/28452
I'm not entirely sure if my solution is the correct way to do it or if I should add some logic to emitter for creating optional properties.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/tsjs-lib-generator/626)

Make HTMLElement.nonce optional

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/overridingTypes.json

I hit a compile error because IDBCursor.primaryKey was incorrectly typed as
`IDBValidKey | IDBKeyRange` instead of just `IDBValidKey`. I fixed it and
manually audited the rest of the instances of `IDBValidKey | IDBKeyRange` and
fixed them.  If there's a better way to fix these other than manual audit based
on my understanding of the IndexedDB API, let me know.
Fixes https://github.com/Microsoft/TypeScript/issues/29070

Remove inappropriate IDBKeyRange usages from lib.dom.d.ts.

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json
inputfiles/idl/Clipboard.widl
inputfiles/idlSources.json
inputfiles/overridingTypes.json
inputfiles/removedTypes.json

I messed up the merge of #628, so I'm trying again.

Add Clipboard Interfaces to idlSources

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json

Fixes Microsoft/TypeScript#17828

Add missing HTML tags

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json

Per the specs:
https://www.w3.org/TR/cssom-view-1/#event-summary
https://html.spec.whatwg.org/multipage/indices.html#event-select
Fixes Microsoft/TypeScript#18355

Use Event for scroll/select events

---

package-lock.json
package.json

#556 forced to use TS 2.9.2 because of temporary bug on TS 3.0. This PR reverts it.

Return to typescript@next

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/overridingTypes.json

Similar solution to https://github.com/Microsoft/TSJS-lib-generator/pull/332 to allow URLs to be passed into a Worker constructor.
Fixes https://github.com/Microsoft/TypeScript/issues/28397

Allow URLs in Worker constructor

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json
src/emitter.ts

fix: redefine ElementTagNameMap to fix SVGElementTagNameMap

---

baselines/dom.generated.d.ts
inputfiles/idl/CSS Images.widl
inputfiles/idlSources.json
package.json

Adding `style.imageOrientation` and `style.imageRendering`.
PS: b08845e is because the previous change prevents adding new types via `idlSources.json`, where any new field causes ENOENT when building before fetching.

Add CSS Images types

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json

It is `[n: number]: Window`.
Fixes Microsoft/TypeScript#30187

Add number index signature to Window

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/addedTypes.json
inputfiles/overridingTypes.json
src/emitter.ts
src/idlfetcher.ts
src/index.ts

1. `ElementCreationOptions` is already in IDL
1. `ParentNode` is already in IDL
1. `BroadcastChannelEventMap` is already defined elsewhere (we currently have two of them)
1. `NodeSelector` has been merged into `ParentNode` and is not used anymore
`ImageBitmapOptions` is covered by #571.

Remove redundant added types

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json

`HTMLMainElement` is not defined in any spec and no browser supports it.

Remove HTMLMainElement

---

baselines/dom.generated.d.ts
inputfiles/idl/Intersection Observer.widl
inputfiles/idlSources.json
package.json

Adds a new field `intersectionRatio` and more.

Update Intersection Observer types 

---

baselines/dom.generated.d.ts

From the [specification](https://www.w3.org/TR/DOM-Level-3-XPath/xpath.html#XPathResult):
> The value of this single node result, which may be null.

Allow null for XPathResult.singleNodeValue

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/idl/Streams.widl
inputfiles/overridingTypes.json

This updates the type definitions for Streams to [spec version `46c3b89` of 7 November 2018](https://github.com/whatwg/streams/tree/46c3b89dd3aff28b2fc381dd1d397c12b4fb8a16) ([spec text](https://streams.spec.whatwg.org/commit-snapshots/46c3b89dd3aff28b2fc381dd1d397c12b4fb8a16/)).
* `PipeOptions` now takes an optional `AbortSignal`, to allow aborting an ongoing pipe operation started with `ReadableStream.pipeTo()` or `.pipeThrough()`
This also removes the (accidentally exposed) `ReadableStreamBYOBReader` constructor. [The spec defines](https://streams.spec.whatwg.org/commit-snapshots/46c3b89dd3aff28b2fc381dd1d397c12b4fb8a16/#globals) that this constructor should not be exposed.

Update Streams to spec version 46c3b89

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json
inputfiles/idl/Media Capture and Streams.widl
inputfiles/idlSources.json
inputfiles/overridingTypes.json
inputfiles/removedTypes.json

* `ConstrainLong`/`ConstrainLongRange`/`LongRange` are renamed to `*ULong*`
* `OverconstrainedError`/~~`OverconstrainedErrorEvent`~~ are added
* etc.
Removed `OverconstrainedErrorEvent` because no browser implements it (except Edge which implements it in its older name `MediaStreamErrorEvent`).

Add Media Capture and Streams types

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json
inputfiles/idl/DeviceOrientation Event.widl
inputfiles/idlSources.json
inputfiles/removedTypes.json

Adds `deviceorientationabsolute` event and renames types per the spec.
`requestPermission()` and additional constructors are excluded because there is no implementers yet.

Add DeviceMotion event types

---

baselines/dom.generated.d.ts
baselines/dom.iterable.generated.d.ts
inputfiles/addedTypes.json
inputfiles/idl/SVG - Basic Shapes.widl
inputfiles/idlSources.json

Adds detail to the inheritance hierarchy, so that it fixes Microsoft/TypeScript#29573

Add SVG - Basic Shapes section

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json
inputfiles/overridingTypes.json

As of https://github.com/Microsoft/TypeScript/issues/30368 this removes deprecation flag in `SVGSVGElement` for the properties `setCurrentTime`, `pauseAnimations`, `unpauseAnimations`, and `getCurrentTime`. It also adds the method `animationsPaused(): boolean`.
(closes https://github.com/Microsoft/TypeScript/issues/30368)

Remove deprecation of methods and add missing method in SVGSVGElement.

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/overridingTypes.json
src/emitter.ts
src/widlprocess.ts

Matches MessagePort, ServiceWorker and DedicatedWorkerGlobalScope, followup to #679
Fixes microsoft/Typescript#31448

Add Worker.postMessage override

---

baselines/dom.generated.d.ts
inputfiles/idl/Touch Events.widl

They are already removed from Chrome.

Remove createTouch* APIs

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json
src/emitter.ts
src/types.d.ts
src/widlprocess.ts

According to https://github.com/Microsoft/TypeScript/issues/30716 focusin/focusout are missing from `GlobalEventHandlersEventMap`.
I have added `onfocusin` and `onfocusout` to `GlobalEventHandlers` and the events `focusin` and `focusout`, which were supposed to be mapped, but they haven't shown up in `GlobalEventHandlersEventMap`, so I could use a small help!
@saschanaz, I've searched in the history and I noticed that in https://github.com/Microsoft/TSJS-lib-generator/pull/674 you've managed to add `deviceorientationabsolute` to `WindowEventMap`. How did you achieve that? I think I'm missing some detail here...
Also, I noticed that `onfocus` has a comment explaining its purpose, would it make sense to include comments also for `onfocusin` and `onfocusout`?
Fixes …

Add focusin/focusout to GlobalEventHandlers

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json
src/widlprocess.ts

This now matches `querySelector`. Allows:
```js
element.closest<HTMLAnchorElement>('.lol')
// => HTMLAnchorElement
```

Add generic support to `Element.closest()`

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/addedTypes.json
inputfiles/overridingTypes.json
inputfiles/removedTypes.json
src/emitter.ts
src/helpers.ts

This type doesn't exist, but it did before about a year ago, and is useful until we parametrise ProgressEvent with subtype properties.
Also fixes variable names in `merge`, which had source and target backward, making for some confusing reading.
Fixes microsoft/Typescript#25510

Restore FileReaderProgressEvent

---

baselines/dom.iterable.generated.d.ts
src/emitter.ts
src/widlprocess.ts

Closes https://github.com/Microsoft/TypeScript/issues/28198.

Emit iterable arguments for ES2015+

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/overridingTypes.json

Fixes https://github.com/microsoft/TypeScript/issues/31490
This PR adds `null` as a valid type to all IndexedDB API methods that accept an optional query param followed by another argument.
It also standardizes on the name "query" everywhere (previously it was sometimes called "query" and sometimes called "range"), as "query" is what's used in [Web IDL in the spec](https://w3c.github.io/IndexedDB/#object-store-interface).
*__Note__: I was getting an error when running the build step that appears to be unrelated to my changes (it fails on master as well). I'm not sure what (if anything) I should do about that.*

Add null types to optional IDB query parameters

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json
inputfiles/idl/UI Events.widl
inputfiles/idlSources.json

Add `InputEvent` and removes some nonstandard types.
Closes #705. Sorry 😅

Add UI Events types

---

baselines/dom.generated.d.ts
inputfiles/idl/Credential Management.widl
inputfiles/idlSources.json
inputfiles/removedTypes.json

Excluding `FederatedCredential` and `PasswordCredential` which is currently only implemented in Chromium.

Add Credential Management types

---

README.md

Closes #611 
I think this reflects the recent situation.

Revise the condition to add specs

---

baselines/dom.generated.d.ts
inputfiles/idl/Web Authentication.widl
inputfiles/idlSources.json

Add Web Authentication types

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json
inputfiles/idl/CSS Masking.widl
inputfiles/idlSources.json
inputfiles/removedTypes.json

Excluding properties that lack multiple implementations.

Add CSS Masking types

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/addedTypes.json
inputfiles/comments.json
inputfiles/overridingTypes.json
src/emitter.ts
src/types.d.ts
src/widlprocess.ts

Parameterize ProgressEvent

---

package-lock.json
package.json

The new version of @types/node avoids the new generator types introduced recently in typescript@next.

Update @types/node and typescript dependency

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/addedTypes.json
inputfiles/overridingTypes.json

Should fix some DefinitelyTyped errors in https://github.com/microsoft/TSJS-lib-generator/pull/452#issuecomment-501029800.
Closes https://github.com/microsoft/TypeScript/issues/19816

Use globalThis for .window/.self

---

inputfiles/comments.json

Something changed in the way we print comments and the carriage return (\r) was getting included in the output. They shouldn't be in the input anymore either, so this commit removes them.
The baselines are already normalised so don't show any changes.

Remove carriage return from comments

---

baselines/dom.iterable.generated.d.ts
src/emitter.ts

This fixes a compatibility issue with Node.js 8/10 where `.sort()` behaves differently with Node.js 12, by doing proper sort by name.
Thanks @jeffryang24 and sorry for the inconvenience! (https://github.com/microsoft/TSJS-lib-generator/pull/700#issuecomment-502342018)

Sort members on dom.iterable.generated.d.ts

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/idl/WebAssembly JavaScript Interface.widl
inputfiles/idl/WebAssembly Web API.widl
inputfiles/idlSources.json

Also adds WebAssembly Web APIs for `instantiateStreaming` and `compileStreaming` (which are now stable).

Upgrade WebAssembly JS IDLs

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/overridingTypes.json

Improve WebAssembly.instantiateStreaming

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
src/emitter.ts

Should ease future reviewing by preventing drastic order changes as in #700.

Sort `implements`

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.json

This PR simply fixes a couple of inaccuracies that were introduced as overrides for CSSOM.
Should be fairly self-explanatory, but feel free to let me know if you have any questions/concerns.
Related:
- https://drafts.csswg.org/cssom-view/#dom-element-getclientrects
- https://drafts.csswg.org/cssom-view-1/#dom-element-getboundingclientrect

fix inaccurate overrides for CSSOM

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/overridingTypes.json

Based on #755 and #766, improves imports param in constructor instead.

Improve WebAssembly.Instance constructor

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/overridingTypes.json

It can be inferred from the first two.
Fixes Microsoft/Typescript#33266

Make ImageData(Uint8ClampedArray)'s 3rd param optional

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json

fixes https://github.com/microsoft/TypeScript/issues/34511

update types rejection handled

---

package-lock.json
package.json

It's used by baseline-accept script, but not referenced in dependencies and so fails to run on fresh checkout.

Add missing `cpx` dependency

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.json

To fix / finish off the pull request #619 .

Override Node previousSibling to be type of ChildNode.

---

baselines/dom.generated.d.ts
inputfiles/removedTypes.json

iOS Safari 13 Beta 6 has shipped with permission API for DeviceMotionEvent and DeviceOrientationEvent, see:
https://developer.apple.com/documentation/safari_release_notes/safari_13_beta_6_release_notes#3314664

Allow requesting permission for device orientation

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.json
src/emitter.ts

Browsers without touch support (e.g., Firefox/Chrome on desktop) will not have `ontouch*` events defined on `window`, so the current type definition is not correct.

Makes the `ontouch*` events on window optional.

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/addedTypes.json
inputfiles/idl/Streams.widl
inputfiles/overridingTypes.json
src/emitter.ts
src/types.d.ts

This PR improves the type definitions for [Streams](https://streams.spec.whatwg.org/):
* Align `ReadableStreamReadResult` with the new [`IteratorResult`](https://github.com/microsoft/TypeScript/blob/v3.6.2/src/lib/es2015.iterable.d.ts#L21) definition from TypeScript 3.6. It is now equivalent to `IteratorResult<T, T | undefined>`, but since the DOM types cannot depend on `es2015.iterable`, I needed to add my own `typedef` with a union type. Fortunately, TypeScript will recognize these as equivalent thanks to its structural type system. 😄 Since this is a *generic* type alias, I have updated the emitter to support type parameters for `typedef`s.
* Add chunk types to `TextEncoderStream` and `TextDecoderStream` from [the Encoding standard](https://encoding.spec.whatwg.org/). Their `readable` …

Improve Streams

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json
inputfiles/overridingTypes.json

At work, we found a couple of incorrect and/or missing types while dealing with [HTML media elements](https://html.spec.whatwg.org/multipage/media.html) and [EME](https://www.w3.org/TR/encrypted-media/). This PR fixes some of these types.

Random fixes for HTML media and EME

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/comments.json

Description taken from https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/toString.

Document URLSearchParams.toString()

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.json

Previously it was a call signature, but this is not correct. I'm not sure if `HTML - Custom Elements.widl` is wrong or whether our interpretation of it is wrong. A call signature does not match actual usage or the semantics as implemented by Chrome, however.

customElement.define's 2nd parameter is a constructor

---

README.md

Notes -> Prose from our pairing session

Add potential hueristics for the README

---

baselines/dom.generated.d.ts
inputfiles/idl/CSS Cascading and Inheritance.widl
inputfiles/idlSources.json

Adding the CSS Cascading and Inheritance property.
Fixes https://github.com/microsoft/TypeScript/issues/37215

Add CSS Cascading and Inheritance

---

baselines/dom.generated.d.ts
inputfiles/removedTypes.json

Fixes #748 
As described in https://html.spec.whatwg.org/multipage/system-state.html#NavigatorID-partial, this is only available by default in Firefox.

Remove Gecko specific Navigator members

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.json

Follow-up to #715
With #819 this change allows 
```ts
declare const element: Element;
const isInput = element instanceof element.ownerDocument.defaultView!.HTMLInputElement;
```
Still requires non-null assertion which is fine. Above code will never be sound since defaultView might not be available. This is, at least for my purpose, alright.
Currently I simply have to `@ts-ignore` `element.ownerDocument.defaultView.HTMLInputElement`.

fix(dom): intersect defaultView with globalThis

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json

> The ownerDocument attribute’s getter must return null, if this is a document, and this’s node document otherwise.
-- https://dom.spec.whatwg.org/#dom-node-ownerdocument
Closes https://github.com/microsoft/TypeScript/issues/36262

fix(dom): narrow ownerDocument in specific Node interfaces

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json

Noticed that there are problems with in `addedTypes.json` (thanks VS Code!) which were related to duplicated entries in `interfaces` > `interface`.
I've removed blocks with `cloneNode` and re-run patched helper script to bring them back to existing nodes.
Updated baselines should now contain proper overrides and elements names that were skipped because of duplicated keys later in JSON.
Related to #811

Fix duplicates after merge in addedTypes.json

---

baselines/dom.generated.d.ts
inputfiles/idl/Web Share.widl
inputfiles/idlSources.json

Fixes https://github.com/microsoft/TypeScript/issues/18642.

Add Web Share types

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.json

From specifically a `[]` (a 0 length tuple) to an `any[]`

Fix the HTMLElement constructor override

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json

They make `@types/tablesorter`, a jquery dependent, invariant in a complex way that I have yet to figure out. I'm reverting this change for 3.9 until I
have time to see how likely other projects are to encounter the problem.
@orta @DanielRosenwasser

Remove clone node overrides

---

inputfiles/idlSources.json

The original https://w3c.github.io/speech-api/ has been replaced with new one.

Fix brokenLinks of speech API

---

baselines/dom.generated.d.ts
inputfiles/idl/DOM.commentmap.json
inputfiles/idl/DOM.widl

`document.origin` has been marked as obsolete and now is removed from the spec. Firefox and Chrome dropped the support, while Safari still supports it.
The IDL change marks `initCustomEvent` and `createEvent` as historical, should they marked as `@deprecated`? Previously the answer was yes (as we mark the whole Compatibility spec as `@deprecated` and also several others), but maybe time to make sure again.

Update DOM types

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.json

SVGSVGElement.getEnclosureList and SVGSVGElement.getIntersectionList accept `null` as the reference element.
There isn't much doc about it (missing docs on MDN) but this [page (IE docs)](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/platform-apis/ff974230(v%3Dvs.85)) states that " If this parameter is null, all matching elements are included in the returned list.".
The [webkit docs](https://developer.apple.com/documentation/webkitjs/svgsvgelement/1634515-getintersectionlist) also show this argument to be optional (undefined instead of null but the result is the same).
You can see some reference to it in a SO answer as well: https://stackoverflow.com/a/29398962/2718736
I hope it's the right place to update the types?

referenceElement can be null

---

inputfiles/idl/Web Background Synchronization.widl
inputfiles/idlSources.json
package.json

* WBS spec changed their repository name
* `widlprocess.ts` has type errors which are fixed by `@types/webidl2` update

Fix build errors

---

baselines/dom.generated.d.ts
inputfiles/idl/Web VisualViewport API.widl
inputfiles/idlSources.json

Fixes [#37585](https://github.com/microsoft/TypeScript/issues/37585)
All tests passed.
The Visual Viewport API is designed to provide an explicit mechanism for developers to query and potentially modify the properties of the visual viewport. It also introduces events that allow the page to listen for changes in the visual viewport, allowing UX that explicitly wants to react to these changes to do so. For example, the page could keep a small text-formatting bar above the OSK.

Support web API VisualViewport

---

baselines/webworker.generated.d.ts
inputfiles/overridingTypes.json

fixes https://github.com/microsoft/TypeScript/issues/36705
it should be https://w3c.github.io/ServiceWorker/#dom-clients-get
`  get(id: string): Promise<Client | undefined>; `

Refine webworker interface clients get signature

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json

See: https://developer.mozilla.org/en-US/docs/Web/API/SpeechRecognitionErrorEvent

WebSpeech's SpeechRecognition onerror incorrectly reports ErrorEvent as event

---

.github/workflows/ci.yml

Repo moved to GitHub Actions with https://github.com/microsoft/TSJS-lib-generator/pull/862.
But that's also when `master` stopped being tested.

ci: ensure master branch is also tested

---

baselines/webworker.iterable.generated.d.ts
src/emitter.ts
src/index.ts

Generate Worker iterable types

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/addedTypes.json
inputfiles/knownTypes.json
inputfiles/overridingTypes.json

The latter was removed in 2016: https://github.com/w3c/webcrypto/pull/16 with the former being in the current spec: https://w3c.github.io/webcrypto/#hkdf-params

Fix HkdfParams use and remove HkdfCtrParams

---

baselines/dom.generated.d.ts
baselines/dom.iterable.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/overridingTypes.json
src/emitter.ts

The field tends to shadow upstream updates to the methods. This patch is the first step to reduce such uses.

Remove redundant override-signatures

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/overridingTypes.json

Without this change the return value is always Promise<CryptoKeyPair|CryptoKey>
and never the more specific types.

Ensure the most generic overload of SubtleCrypto generateKey comes last

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.json

Now types of dropEffect and effectAllowed are string but comments restrict their values like below.
> The possible values are "none", "copy", "link", and "move".
> The possible values are "none", "copy", "copyLink", "copyMove", "link", "linkMove", "move", "all", and "uninitialized",
So I updated their types according to the comments.

Restrict possible values of DataTransfer.dropEffect and DataTransfer.effectAllowed.

---

baselines/webworker.iterable.generated.d.ts

This updates webworker.iterable.generated.d.ts to fix `npm run test`
-> `npm run build` -> `npm run baseline-accept`
Fixes #911

Add IDBDatabase to webworker.iterable

---

baselines/dom.generated.d.ts
baselines/webworker.iterable.generated.d.ts
inputfiles/comments.json
inputfiles/removedTypes.json

Just activate HTMLVideoElement playsinline attribute for solve this problem.
https://webkit.org/blog/6784/new-video-policies-for-ios

Just activate HTMLVideoElement playsinline attribute.

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json

It's needed to fix cross browsing issue(support IE)
Fixes https://github.com/microsoft/TypeScript/issues/15228

Add keyCode attribute to KeyboardEventInit

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json
inputfiles/idl/Web Speech API.widl
inputfiles/removedTypes.json
src/index.ts

Changed the type of the SpeechRecognition event handler for error from ErrorEvent to SpeechRecognitionErrorEvent to match the [API](https://wicg.github.io/speech-api). This adds the types `SpeechRecognitionErrorEvent` and `SpeechRecognitionErrorCode` back in and resolves [this issue](https://github.com/microsoft/TypeScript/issues/37046). 
If it's a potential problem, this reverses some of the changes made [here](https://github.com/microsoft/TypeScript-DOM-lib-generator/commit/1f859ddee3b17f409837694ff89d8d0e7d70f13f).

Update Web Speech API to match idl

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json

Added event handlers ongamepadconnected and ongamepaddisconnected to add their corresponding events to lib.dom.d.ts and resolve [this issue](https://github.com/microsoft/TypeScript/issues/39425). The event handler names were taken from [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window/ongamepadconnected).

Added event handlers for gamepadconnected GamepadEvent

---

baselines/dom.generated.d.ts
inputfiles/idl/Pointer Events.widl
inputfiles/idlSources.json

Fixes https://github.com/microsoft/TypeScript/issues/37990
Level 3 Editor's Draft URL: https://w3c.github.io/pointerevents/
This version includes a definition for getCoalescedEvents, which is supported
in [Chrome 58, Edge 79, and Firefox 59][mdn-compat].
It also adds definitions for getPredictedEvents and pointerrawupdate which are
not yet supported in any browser.
[mdn-compat]: https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent/getCoalescedEvents

Update Pointer Events IDL to Level 3 Editor's Draft.

---

baselines/webworker.generated.d.ts
inputfiles/overridingTypes.json

When specifically querying for clients of type `window`, return the specific `WindowClient` type instead of the generic `Client` type.

Add conditional return type for Clients.matchAll

---

inputfiles/idl/Resize Observer.widl
inputfiles/idlSources.json

However, i got an error when generating the types for Resize Observer:
```
bareMessage: 'Attributes cannot accept sequence types',
context: 'Syntax error at line 23, since `interface ResizeObserverEntry`:\n' +
' attribute sequence<ResizeObserverSize> borderBoxSize;\n' +
```
fixes https://github.com/microsoft/TypeScript/issues/37861

feat: add resize-observer typs

---

baselines/dom.generated.d.ts
inputfiles/idl/WebRTC Stats.widl
inputfiles/idlSources.json

This proposes bringing in the WebRTC Stats spec. The driver here is updating the `RTCStatsType` enum values, as described in https://github.com/microsoft/TypeScript/issues/36650, but there are other changes that the README-recommended `fetch-idl` process brings in as well. 
My initial thinking was that getting all the spec updates in is preferable, but I'm also not totally sure where browser adoption is for this spec, so I'm not sure what level belongs in TypeScript. Could isolate to just `RTCStatsType` to mitigate risk.
Side note: importing this spec via the README instructions did require a bit of editing to remove the text "WebIDL" in front of each WebIDL block, due to a `.idlHeader` element with that text appearing inside the `.idl` code block. It looks like a number of other specs …

Add WebRTC Stats spec

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json

`GlobalEventHandlers` were missing `"compositionstart"`, `"compositionupdate"` and `"compositionend"`, which caused errors when trying to use a function type that relied on getting even object types from that type.
(I should note that I don't really know what I'm doing here, and just searched for the other event names and added similar declarations in what looked like the appropriate place.)

Add composition events to GlobalEventHandlers

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.json

`frameElement` is `null` if the window is the top-level window, or if the window is embedded in a document that has a different origin.
See https://developer.mozilla.org/en-US/docs/Web/API/Window/frameElement

Correct type of Window.frameElement

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/overridingTypes.json

Allow URL object to be used in `ServiceWorkerContainer#register`. Similar as #600 which was for Worker constructor.
Fixes microsoft/TypeScript#41980

Allow URL in ServiceWorkerContainer#register

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.json
inputfiles/overridingTypes.json

Reverts microsoft/TypeScript-DOM-lib-generator#885 - so that we can release 4.2 without this, it's not that this represents an end to the idea, but it is too breaking to DefinitelyTyped and so it's likely to be very breaking to the rest of the TS/JS ecosystem and we'd like to give it a longer look.

Reverts microsoft/TypeScript-DOM-lib-generator#885 - dom query changes

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/addedTypes.json

Correctly implements the hotfix I added to https://github.com/microsoft/TypeScript/pull/42230

Make ImportMeta's url match the version in @types/node

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.json

Fixes [microsoft/TypeScript#42433](https://github.com/microsoft/TypeScript/issues/42433)
I have not found a suitable IDL for window.opener, but you can find [here ](https://html.spec.whatwg.org/multipage/browsers.html#dom-opener) that window.opener can be specified as WindowProxy or null.

fix: `window.opener` should be not be typed as any

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/addedTypes.json

(This is my first time contributing lib type updates, please let me know if I did anything wrong.)
Closes microsoft/TypeScript#42182.
[MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Memory/Memory#Parameters)
Note that this parameter is missing from the [spec](https://www.w3.org/TR/2019/REC-wasm-js-api-1-20191205/#memories).
[browser-compat-data](https://github.com/mdn/browser-compat-data/blob/5c9fce3086e91e9994ce8e8b37791c34512718e9/javascript/builtins/webassembly/Memory.json#L112)

feat(WebAssembly): Add `shared: boolean` for `MemoryDescriptor` dict

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.json

The signature for RTCPeerConnection.setLocalDescription has been overriden, as of #386, to have a mandatory argument. This is no longer the case; see specs here:
https://w3c.github.io/webrtc-pc/#dom-peerconnection-setlocaldescription
https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/setLocalDescription#Parameters
This PR makes it optional, as it should be.
Resolves #875
Resolves https://github.com/microsoft/TypeScript/issues/41939
Resolves https://github.com/microsoft/TypeScript/pull/39142
Props to @jcc10 and @Simonwep for finding this bug before me, but trying to fix it by modifying the generated declaration files, instead of here (as per [these instructions](https://github.com/Microsoft/TypeScript/blob/master/CONTRIBUTING.md#modifying-generated-library-files)). I think …

Fix RTCPeerConnection override

---

.github/workflows/ci.yml
.github/workflows/test_typescript.yml
package.json
src/emitter.ts
src/helpers.ts
tsconfig.json

Because it's 2021. Also [happy WFH anniversary](https://twitter.com/SeanOnTwt/status/1367631192271450114).
Upstreaming from types-web...

Remove redundant helper functions

---

baselines/dom.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/idl/Server Timing.widl
inputfiles/idlSources.json

In the hopes of getting a discussion going around [PerformanceServerTiming](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceServerTiming) this implements the basic types as specified in [the WD spec](https://w3c.github.io/server-timing/#the-performanceservertiming-interface).
From the contributor guidelines:
From the [browser compat table on mdn](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceServerTiming#browser_compatibility) this API is available in Firefox 61, Chrome 65, Edge 79
[![browser compat table](https://user-images.githubusercontent.com/118266/109152914-0a68b000-7764-11eb-9d18-21b590909a3b.png)](https://developer.mozilla.org/en-US/docs/Web/API/PerformanceServerTiming#browser_compatibility)

add performanceservertiming

---

baselines/dom.generated.d.ts
package.json
src/emitter.ts
src/widlprocess.ts

Thanks to https://github.com/microsoft/TypeScript/pull/42425
This turns out to be less interesting than I expected because of the setter type limitation where the getter type must be assignable to the setter type. Thus the following can't be supported:
```webidl
[Exposed=Window]
interface CSSStyleRule : CSSRule {
attribute CSSOMString selectorText;
[SameObject, PutForwards=cssText] readonly attribute CSSStyleDeclaration style;
};
```
```ts
interface CSSStyleRule extends CSSRule {
selectorText: string;
get style(): CSSStyleDeclaration;
set style(cssText: string); // error!
}
```
```ts
document.body.style = "display: none" // thus still an error 🤔
```
Probably worth to file an issue, or does TS team think this is not a very interesting case?

feat(emitter): support differing accessor types

---

.github/CODEOWNERS
.github/workflows/codeowners-merge.yml

By using https://github.com/OSS-Docs-Tools/code-owner-self-merge we get to give enough rights to @saschanaz while still conforming to the Microsoft security guidelines

Gives @saschanaz the ability to merge PRs which affect src/baselines/inputfiles

---

.github/workflows/ci.yml
.github/workflows/deploy.yml
.github/workflows/test_typescript.yml
.github/workflows/update-core-deps.yml

Add `cache` to workflows using `actions/setup-node`
`setup-node` GitHub Action just released a new option to add cache to steps using it.
You can find the details here: https://github.blog/changelog/2021-07-02-github-actions-setup-node-now-supports-dependency-caching/
---
🤖 This PR has been generated automatically by [this octoherd script](https://github.com/oscard0m/octoherd-script-add-cache-to-node-github-action), feel free to run it in your GitHub user/org repositories! 💪🏾

ci(workflow): add cache to workflows using actions/setup-node

---

.github/workflows/codeowners-merge.yml

Should probably fix the pings in https://github.com/Scharkee/TypeScript-DOM-lib-generator/pull/1#issuecomment-875600459

Scope the action to only run on our repo

---

baselines/dom.generated.d.ts
src/build/emitter.ts

Fixes https://github.com/microsoft/TypeScript/issues/44039 
If there is an entity comment and a depreciation comment, they will be merged into one.
[This is a diff ](https://github.com/microsoft/TypeScript-DOM-lib-generator/pull/1011/files#diff-d57c51d024219b9f37e6b42df127db25f700acbaade23ce1edcecda2853b995c)for one of the generated files, `dom.generated.d.ts`, before and after this change.

Merge comment and depreciation notice

---

.github/workflows/codeowners-merge.yml

It currently is [causing syntax error](https://github.com/microsoft/TypeScript-DOM-lib-generator/actions/runs/1015022267). @orta

Wrap the repository name in codeowner checker

---

deploy/createTypesPackages.mjs
deploy/deployChangedPackages.mjs
src/changelog.ts
src/version.ts

Add support for re-using the CHANGELOG infra for the releases - https://github.com/microsoft/TypeScript-DOM-lib-generator/releases

Generate changelogs per release

---

README.md
deploy/createTypesPackages.mjs
deploy/deployChangedPackages.mjs
deploy/migrate.mjs
deploy/versionChangelog.mjs
package.json
src/changelog.ts
src/version.ts

https://github.com/microsoft/TypeScript-DOM-lib-generator/commit/97f733707a840650c8995f290a28dc3ee44b502a is the only commit which matters (I just wanted to build on top of #1056 )

Documents the release to TS process, and adds support for easily generating a CHANGELOG for 2 arbitrary versions 

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.jsonc

This is copying what `document.getElementById` and `document.body.ownerDocument` currently looks like.
Regressed by b598925.
Fixes the DocumentFragment issue raised in #1067.

Add HTMLElement-returning getElementById to DocumentFragment

---

baselines/dom.generated.d.ts
baselines/dom.iterable.generated.d.ts
package-lock.json
src/build/bcd/keep-alive.ts

@orta could you double check that the token below has the `public-repo` permission, since [it's failing to open PRs](https://github.com/microsoft/TypeScript-DOM-lib-generator/runs/3092249820?check_suite_focus=true)? Thanks!
https://github.com/microsoft/TypeScript-DOM-lib-generator/blob/1f0846bdf369f4d78876465ec7d50ec66aae3cfa/.github/workflows/update-core-deps.yml#L35

Update webref/idl to 2.2.8

---

baselines/dom.generated.d.ts
baselines/serviceworker.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/addedTypes.jsonc
package-lock.json
src/build/bcd/keep-alive.ts

Waiting for Orta to update token permission... https://github.com/microsoft/TypeScript-DOM-lib-generator/actions/runs/1062082687

Update bcd to 3.3.12

---

deploy/deployChangedPackages.mjs
package-lock.json
package.json

Fixes #1083
octokit was a phantom dependency 😱

Pass string to createRelease()

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.jsonc

Make ChildNode and ParentNode extend Node again

---

baselines/dom.generated.d.ts
src/build/emitter.ts

Makes exactOptionalPropertyTypes work better with `Window` and `window`

Always emit "| undefined" for optional properties

---

baselines/dom.generated.d.ts
baselines/serviceworker.generated.d.ts
baselines/sharedworker.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/addedTypes.jsonc

Changes `createObjectURL(object: any): string` to `createObjectURL(object: File | Blob | MediaSource): string`.
Makes type declaration inline with the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL).
Fixes #916.

fix(createObjectURL): use MDN type declaration

---

baselines/audioworklet.generated.d.ts
baselines/dom.generated.d.ts
baselines/serviceworker.generated.d.ts
baselines/sharedworker.generated.d.ts
baselines/webworker.generated.d.ts
package-lock.json

Manually update webref/idl to 2.2.10

---

baselines/dom.generated.d.ts
baselines/serviceworker.generated.d.ts
baselines/sharedworker.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/overridingTypes.jsonc

Make DOMException extend Error

---

baselines/dom.generated.d.ts
inputfiles/comments.json
inputfiles/overridingTypes.jsonc

Fixes microsoft/TypeScript#45458

Update HTMLMediaElement.preload type and comment

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.jsonc
unittests/files/htmldocument.ts

Detected in https://github.com/microsoft/TypeScript/issues/45540, where it breaks ant-design. `x instanceof HTMLDocument` no longer works.
This is likely worth fixing before the release of 4.4.
Fixes #1115

Restore HTMLDocument constructor

---

baselines/audioworklet.generated.d.ts
baselines/audioworklet.iterable.generated.d.ts
baselines/dom.generated.d.ts
baselines/dom.iterable.generated.d.ts
baselines/serviceworker.generated.d.ts
baselines/serviceworker.iterable.generated.d.ts
baselines/sharedworker.generated.d.ts
baselines/sharedworker.iterable.generated.d.ts
baselines/webworker.generated.d.ts
baselines/webworker.iterable.generated.d.ts
src/build/widlprocess.ts

It looks like a regression slipped into the `ReadableStream` interface. In TypeScript 4.4, it incorrectly has a `[Symbol.iterator]` method, along with automatic `forEach`/`entries`/`keys`/`values` methods. In reality [`ReadableStream` is an `async iterable<any>`](https://streams.spec.whatwg.org/#readablestream), meaning it has a `[Symbol.asyncIterator]` and `values` method (both returning an async iterator).
Since we don't (yet) have a way to express this, I've changed the emitter to instead ignore `async iterable` declarations, so at least we don't *add* any non-existent methods. Alternatively, we could do this properly: tackle microsoft/TypeScript#29867 and introduce `lib.dom.asynciterable.d.ts`.

Fix ReadableStream incorrectly marked as a sync iterable

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.jsonc

The spec (https://w3c.github.io/mediacapture-record/#event-summary) specifies a specific event type MediaRecorderErrorEvent for the error event.
This ensures we're using it, similar to the dataavailable event.
Fixes #1138 
(I hope this is the correct way to do this 🙂)

Use special type for MediaRecorder error event

---

baselines/dom.generated.d.ts
baselines/serviceworker.generated.d.ts
baselines/sharedworker.generated.d.ts
baselines/webworker.generated.d.ts
src/build/bcd/stable.ts

See https://github.com/mdn/browser-compat-data/issues/12344 for the reasoning.

Exclude features with `version_added: preview`

---

baselines/dom.generated.d.ts
inputfiles/removedTypes.jsonc

Referring to issue #1148. First PR in this repo. Let me know what I have missed. :)

Adds autoGainControl and noiseSuppression properties

---

package-lock.json
src/build/bcd/keep-alive.ts
src/build/bcd/mapper.ts

Update bim and refer to `legacyNamespace`

---

.github/workflows/update-core-deps.yml

To make the bot work with #1127

Try forking first before pushing PR

---

baselines/audioworklet.generated.d.ts
baselines/dom.generated.d.ts
baselines/serviceworker.generated.d.ts
baselines/sharedworker.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/addedTypes.jsonc

These types are actually defined using **ECMA‑262**’s <code><var>NativeError</var></code> object structure:
- <https://webassembly.github.io/spec/js-api/#error-objects>
- <https://tc39.es/ecma262/#sec-nativeerror-object-structure>
---
They’re also exposed everywhere <code>namespace [WebAssembly][namespacedef-webassembly]</code> is.
[namespacedef-webassembly]: https://webassembly.github.io/spec/js-api/#namespacedef-webassembly

fix(WebAssembly): Correct `NativeError` subclass types

---

.github/workflows/update-core-deps.yml

I think `read:org` is only required for other features of `gh` and shouldn't be required for forking itself.

Use lelia/forker instead of gh cli

---

baselines/audioworklet.generated.d.ts
baselines/dom.generated.d.ts
baselines/dom.iterable.generated.d.ts
baselines/serviceworker.generated.d.ts
baselines/sharedworker.generated.d.ts
baselines/webworker.generated.d.ts
src/build/emitter.ts
src/build/types.d.ts
src/build/widlprocess.ts

Add comment for secure-context-only types

---

baselines/audioworklet.generated.d.ts
baselines/dom.generated.d.ts
baselines/serviceworker.generated.d.ts
baselines/sharedworker.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/overridingTypes.jsonc

Add `transfer` type of `StructuredSerializeOptions` for some `postMessage` methods.

Fix: Add `transfer` type of `StructuredSerializeOptions`

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.jsonc
inputfiles/overridingTypes.jsonc

Add types for `CanvasRenderingContext2D.globalCompositeOperation`, which is currently a `string` but should only accept certain values. The acceptable values come from [MDN](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalCompositeOperation).
Reported as a bug in TypeScript's main repo: https://github.com/microsoft/TypeScript/issues/34673

Add more specific types for globalCompositeOperation

---

package.json

When installing dependencies, the following warning comes from `@types/node-fetch`
```bash
npm WARN deprecated @types/node-fetch@3.0.3: This is a stub types definition. node-fetch provides its own type definitions, so you do not need this installed.
```
Included types for `node-fetch` can be seen in the node fetch repository - https://github.com/node-fetch/node-fetch/tree/main/%40types
The `node-fetch` npm package also shows that type declarations are included - https://www.npmjs.com/package/node-fetch

remove unnecessary type dependency

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.jsonc
inputfiles/comments.json

[`loading` attribute for `<img>` element is going to be supported also by Safari](https://webkit.org/blog/12040/release-notes-for-safari-technology-preview-135/), [HTML element: img: loading](https://caniuse.com/mdn-html_elements_img_loading).
- Add a description of [`loading` attribuets for `<img>` element](https://html.spec.whatwg.org/#the-img-element).
- Use [`'eager' | 'lazy'` instead of `string` as a type for `loading` attributes](https://html.spec.whatwg.org/#lazy-loading-attributes)

Improve loading attribute for HTMLImageElement

---

baselines/dom.generated.d.ts
baselines/serviceworker.generated.d.ts
baselines/sharedworker.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/addedTypes.jsonc

This makes them almost as usable as the existing shims at @types/wicg-file-system-access.
To make up the rest of the difference, I tried adding an alias
```ts
type X = FileSystemFileHandle | FileSystemDirectoryHandle
```
But
1. I couldn't come up with a good name for X
2. I couldn't easily figure out how to generate the type alias without it being used somewhere.

Add discriminants to FileSystemHandle subtypes

---

inputfiles/addedTypes.jsonc

`name` is not needed when the interface is already defined.

Make FileSystem*Handle additions smaller

---

baselines/dom.generated.d.ts
baselines/serviceworker.generated.d.ts
baselines/sharedworker.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/overridingTypes.jsonc

The type is defined at https://w3c.github.io/FileAPI/#blob-get-stream
> [...]
> 
> 2. Let _chunk_ be a new Uint8Array wrapping an ArrayBuffer containing _bytes_. If creating the ArrayBuffer throws an exception, then error _stream_ with that exception and abort these steps.
> 3. Enqueue _chunk_ in stream.

Override `Blob.stream()` return type to `ReadableStream<Uint8Array>`

---

baselines/dom.generated.d.ts
baselines/serviceworker.generated.d.ts
baselines/sharedworker.generated.d.ts
baselines/webworker.generated.d.ts
package-lock.json
src/build/helpers.ts
src/build/widlprocess.ts

Manually updating because of #1282. (Not updating to the latest one since it needs more investigation)

Update to bcd@4.1.7

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.jsonc

The DOMContentLoaded event was missing from both the Document and Window interfaces.
https://developer.mozilla.org/en-US/docs/Web/API/Window/DOMContentLoaded_event
https://developer.mozilla.org/en-US/docs/Web/API/Document/DOMContentLoaded_event

Add DOMContentLoaded event to Window and Document

---

baselines/dom.generated.d.ts
baselines/dom.iterable.generated.d.ts
baselines/serviceworker.generated.d.ts
baselines/serviceworker.iterable.generated.d.ts
baselines/sharedworker.generated.d.ts
baselines/sharedworker.iterable.generated.d.ts
baselines/webworker.generated.d.ts
baselines/webworker.iterable.generated.d.ts
inputfiles/overridingTypes.jsonc
unittests/files/keyusage.ts

SubtleCrypto methods don't mutate input array, so we can allow ReadonlyArrays to be passed
This makes also this syntax possible:
```
const keyUsages = ['decrypt'] as const
await generateKey(..., keyUsages)
```
which wasn't possible before

Change KeyUsage[] in SubtleCrypto to ReadonlyArray<KeyUsage>

---

baselines/dom.generated.d.ts
baselines/serviceworker.generated.d.ts
baselines/sharedworker.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/removedTypes.jsonc

We now get support in FF Nightly and Safari TP so I think this can be added now. (Not 100% shure as we only have it stable in chromium)
see https://developer.mozilla.org/en-US/docs/Web/API/NavigationPreloadManager#browser_compatibility
feel free to close this (or don't merge it) until we get 2 stable implementations...

feat: add serviceworkerRegistration.navigationPreload

---

baselines/audioworklet.generated.d.ts
baselines/dom.generated.d.ts
baselines/dom.iterable.generated.d.ts
baselines/serviceworker.generated.d.ts
baselines/sharedworker.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/overridingTypes.jsonc
inputfiles/removedTypes.jsonc
package-lock.json
src/build/bcd/keep-alive.ts

Manually update BCD to 4.1.12

---

baselines/dom.generated.d.ts
inputfiles/addedTypes.jsonc
inputfiles/comments.json

Fixes https://github.com/microsoft/TypeScript/issues/42266
Look like the `HTMLStyleElement.disabled` property is defined in [the specs](https://www.w3.org/TR/DOM-Level-2-HTML/html.html#ID-16428977), also available on every browser, [according to MDN](https://developer.mozilla.org/en-US/docs/Web/API/HTMLStyleElement#browser_compatibility).

Add the missing "disabled" property to HTMLStyleElement

---

.github/workflows/update-core-deps.yml
deploy/onUpdateFailure.js

Ping @saschanaz when update-core-deps fails

---

baselines/dom.generated.d.ts
baselines/dom.iterable.generated.d.ts
baselines/serviceworker.generated.d.ts
baselines/serviceworker.iterable.generated.d.ts
baselines/sharedworker.generated.d.ts
baselines/sharedworker.iterable.generated.d.ts
baselines/webworker.generated.d.ts
baselines/webworker.iterable.generated.d.ts
inputfiles/overridingTypes.jsonc
inputfiles/removedTypes.jsonc

- close https://github.com/microsoft/TypeScript/issues/48601
- close https://github.com/microsoft/TypeScript/issues/48553

fix: `waitUntil` and `transaction` type

---

baselines/audioworklet.generated.d.ts
baselines/dom.generated.d.ts
baselines/serviceworker.generated.d.ts
baselines/sharedworker.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/addedTypes.jsonc
inputfiles/overridingTypes.jsonc
inputfiles/removedTypes.jsonc
unittests/files/streams.ts

[With Firefox 102 adding support for readable byte streams](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/102), we now have two browser engines (Chromium and Gecko) shipping this feature. This means we can finally add official type definitions! 😁
Most of work was already done in #890 but then those types had to be removed. This PR brings them back, and hopefully they'll stay this time around. 😅

Add readable byte streams

---

baselines/audioworklet.generated.d.ts
baselines/dom.generated.d.ts
baselines/dom.iterable.generated.d.ts
baselines/serviceworker.generated.d.ts
baselines/serviceworker.iterable.generated.d.ts
baselines/sharedworker.generated.d.ts
baselines/sharedworker.iterable.generated.d.ts
baselines/webworker.generated.d.ts
baselines/webworker.iterable.generated.d.ts
inputfiles/addedTypes.jsonc
inputfiles/overridingTypes.jsonc
inputfiles/removedTypes.jsonc
package-lock.json
src/build/emitter.ts
src/build/helpers.ts

The mass removal of RTC items in removeTypes reflects https://github.com/w3c/webrtc-stats/pull/622 but also the much better implementation status.
Fixes #1370
Fixes #1390

Manually update to webref/idl@3.17.0

---

inputfiles/addedTypes.jsonc

From the spec https://w3c.github.io/IndexedDB/#ref-for-fire-a-version-change-event%E2%91%A1
From MDN https://developer.mozilla.org/en-US/docs/Web/API/IDBOpenDBRequest/blocked_event#event_type
From Chromium https://chromium.googlesource.com/chromium/blink/+/refs/heads/main/Source/modules/indexeddb/IDBOpenDBRequest.cpp#78
From Firefox https://github.com/mozilla/integration-mozilla-inbound/blob/0d01aa29ce350beca861f7d3b7b4df399b246ed0/dom/indexedDB/OpenDatabaseHelper.cpp#L1524

IDB's 'blocked' event should be an IDBVersionChangeEvent

---

baselines/dom.generated.d.ts
baselines/dom.iterable.generated.d.ts
baselines/serviceworker.generated.d.ts
baselines/serviceworker.iterable.generated.d.ts
baselines/sharedworker.generated.d.ts
baselines/sharedworker.iterable.generated.d.ts
baselines/webworker.generated.d.ts
baselines/webworker.iterable.generated.d.ts
inputfiles/overridingTypes.jsonc
inputfiles/removedTypes.jsonc
package-lock.json
src/build/bcd/keep-alive.ts

Update core dependencies

---

README.md

See https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1383#issuecomment-1287927095.
Reasonably confident, but also wondering if there is a tight correspondence between these versions, it's possible there were changes made in third-party sources during this 18-day gap:
Jul 02, 2022: [@types/web@0.0.69](https://github.com/microsoft/TypeScript-DOM-lib-generator/releases/tag/%40types%2Fweb%400.0.69)
July 20, 2022: `v4.8-rc` https://github.com/microsoft/TypeScript/pull/49976

docs: Add `0.0.69`, `4.8 rc`, & `4.8` to table

---

baselines/audioworklet.generated.d.ts
baselines/dom.generated.d.ts
baselines/serviceworker.generated.d.ts
baselines/serviceworker.iterable.generated.d.ts
baselines/sharedworker.generated.d.ts
baselines/sharedworker.iterable.generated.d.ts
baselines/webworker.generated.d.ts
baselines/webworker.iterable.generated.d.ts
inputfiles/addedTypes.jsonc
inputfiles/removedTypes.jsonc
package-lock.json

Manually update to bcd@5.2.9 and idl@3.20.0

---

baselines/dom.generated.d.ts
baselines/serviceworker.generated.d.ts
baselines/sharedworker.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/overridingTypes.jsonc

The websocket spec defines the values of constants like `WebSocket.OPEN`, so they're never going to change. Defining them as literal numbers allows us to write more type-safe code. The same as true for `EventSource` and `FileReader`.
This [same change was made to the `@types/ws` package](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/ws/index.d.ts#L55-L62), which has been very helpful in the NodeJS world. 
I think it's unlikley that this will be a breaking change (?) since `0` and `1` etc. are a subset of `number`, but I could be wrong here. 
There was a discussion at https://github.com/microsoft/TypeScript/issues/25090 where an impossible solution to this problem was proposed (const enums).

better constant definitions for Websocket, EventSource, and FileReader

---

baselines/dom.generated.d.ts
baselines/serviceworker.generated.d.ts
baselines/sharedworker.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/overridingTypes.jsonc

Each context type can only return the relevant context or null.
There are already similar overloads in place for HTMLCanvasElement.getContext.
Relevant part of the HTML spec: https://html.spec.whatwg.org/multipage/canvas.html#dom-offscreencanvas-getcontext

Add overloads for specific context types to OffscreenCanvas.getContext

---

baselines/dom.generated.d.ts
baselines/serviceworker.generated.d.ts
baselines/sharedworker.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/overridingTypes.jsonc

The spec doesn't allow any other values besides these constants for readyState.
See https://w3c.github.io/FileAPI/#dom-filereader-readystate
Not sure if this is the preferred way to narrow the type, I couldn't find any other examples using this pattern. Since this declaration uses constants instead of enums, it shouldn't break any consuming code. The following still compiles:
```ts
fileReader.readyState === 2;
declare const someNumber: number;
fileReader.readyState === someNumber;
```
While using an invalid value here no longer does:
```ts
fileReader.readyState === 5 // TS2367: This comparison appears to be unintentional because the types '0 | 1 | 2' and '5' have no overlap.
```

FileReader.readyState: use FileReader state constants as possible values

---

README.md

TS 4.9 released on November 17, 2022: https://github.com/microsoft/TypeScript/commit/93bd577458d55cd720b2677705feab5c91eb12ce The last change in that ref's tree to `src/lib/dom.generated.d.ts` is from https://github.com/microsoft/TypeScript/pull/51300 on October 25, 2022 which pulled in the types from @types/web 0.0.76, released on October 24, 2022.
Verified by running
```sh
curl "https://raw.githubusercontent.com/microsoft/TypeScript/93bd577458d55cd720b2677705feab5c91eb12ce/src/lib/dom.generated.d.ts" -o ts-types.txt
curl "https://raw.githubusercontent.com/microsoft/TypeScript-DOM-lib-generator/1a77ff811b6b515636c24789ac2cf8f008d4bcbb/baselines/dom.generated.d.ts" -o ts-dom-types.txt
diff ts-types.txt ts-dom-types.txt # no output meaning the files are identicial
```

docs: Add TypeScript 4.9 to table

---

baselines/dom.generated.d.ts
inputfiles/removedTypes.jsonc
package-lock.json

Manally update to webref/idl@3.25.0

---

baselines/audioworklet.generated.d.ts
baselines/dom.generated.d.ts
baselines/dom.iterable.generated.d.ts
baselines/serviceworker.generated.d.ts
baselines/serviceworker.iterable.generated.d.ts
baselines/sharedworker.generated.d.ts
baselines/sharedworker.iterable.generated.d.ts
baselines/webworker.generated.d.ts
baselines/webworker.iterable.generated.d.ts
inputfiles/overridingTypes.jsonc
inputfiles/removedTypes.jsonc
package-lock.json
src/build/bcd/keep-alive.ts

Closes #1503 
Goodness. Look at the commits. This is unprecedentedly huge. Both Apple and Microsoft MUST buy me a coffee.
Mostly coming from https://github.com/mdn/browser-compat-data/pull/18963.

Update to bcd@5.2.38: The unprecedented HUGE Safari 16.4 changes comes here

---

baselines/dom.generated.d.ts
baselines/serviceworker.generated.d.ts
baselines/sharedworker.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/overridingTypes.jsonc
unittests/files/structuredClone.ts

Looks to addresse [this issue](https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1237).
Creates a generic for structuredClone.
[Playground with examples](https://www.typescriptlang.org/play?ssl=3&ssc=3&pln=1&pc=1#code/C4TwDgpgBAsgrsAhgIwDYQDwBUB8UC8UA3gFBRQC0AThIgCYD2AdqiFANoAKUAlk1AGsIIBgDMoWALoAuCV0kBuEgF8lJPsAhVRiAMbQA6n0YB3YmXKWAzsCpxdwODToBhVM0xYCURExA4ACgA3RFQ4CFksABooBjBgHmYrAH5ZAGVbe0dnNK0eUJ4ALwgAeXjEpisASkilZRISUEgoGnpmVgBRAA9EAFswdG8AJVpGFhAMUnImPoioGyo+AHMlckQluaY4XuQtOpwG3STgKAge-vRZVrHO84HoQimoGd65gHJNGzeoi3W5gGYAAwqNRHSonXTuJgPKAmYwMEwAOgWWScEFcUIgATOfXuVSUAHoCVAAALAKwUM6QByUqhUBhUZ7MKC9BAodAkSEeRF-bwAJgAnKDjiy2WgIG4PN44UxTMjMg40RiPBh4EhxRhru0QN1cegcIEudD8SRWer0JLoTyNvyhQ0iVA0gALBhwVB0U50hmnO7oKyIw4ipjMXKLRCFdkwp6iOBMXSyAJVAh4Ij1eokB1kilUiA0rT0xkAOQYJyseQKEfFn …

Make structuredClone generic

---

baselines/dom.generated.d.ts
baselines/serviceworker.generated.d.ts
baselines/sharedworker.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/overridingTypes.jsonc
unittests/files/formData.ts

Addresses [this issue](https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1421)
Adds two overloads to `append` and `set` to prevent runtime errors.

Prevent runtime errors on FormData set and append

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.jsonc

writing code after `location.reload()` is very likely a mistake, since the code will probably never run. 
So this PR changes `location.reload()` to return `never`, akin to `process.exit()` in node

make location.reload() return never

---

baselines/audioworklet.generated.d.ts
baselines/dom.generated.d.ts
baselines/serviceworker.generated.d.ts
baselines/sharedworker.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/overridingTypes.jsonc

`TextEncoderEncodeIntoResult` is defined as a dictionary without `required` members in https://encoding.spec.whatwg.org/#interface-textencoder
```
dictionary TextEncoderEncodeIntoResult {
unsigned long long read;
unsigned long long written;
};
```
However, algorithm for `encodeInto()` (which is the only place the type is referenced) effectively ensures that the properties are always set, described in https://encoding.spec.whatwg.org/#dom-textencoder-encodeinto
>1\. Let read be 0.
>2\. Let written be 0.
>...
>7\. Return «[ "read" → read, "written" → written ]».

Make TextEncoderEncodeIntoResult members required

---

deploy/deployChangedPackages.js

This is really for debugging purpose than anything else, so whatever performs faster fits here.
Fixes #1580.

Use printUnifiedDiff for faster diffing

---

baselines/dom.generated.d.ts
baselines/dom.iterable.generated.d.ts
baselines/serviceworker.generated.d.ts
baselines/serviceworker.iterable.generated.d.ts
baselines/sharedworker.generated.d.ts
baselines/sharedworker.iterable.generated.d.ts
baselines/webworker.generated.d.ts
baselines/webworker.iterable.generated.d.ts
inputfiles/overridingTypes.jsonc

I find myself constantly having to do this:
```ts
const key = await crypto.subtle.generateKey('Ed25519', false, ['sign', 'verify']) as CryptoKeyPair;
```
This PR updates the types so as to indicate that this method always returns a keypair for the algorithm `Ed25519`. It further constrains the type of the `KeyUsages` to just `sign` and `verify` – the only ones allowed by [the spec](https://wicg.github.io/webcrypto-secure-curves/#ed25519).

Add `Ed25519` overload for `SubtleCrypto#generateKey`

---

baselines/dom.generated.d.ts
baselines/serviceworker.generated.d.ts
baselines/sharedworker.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/removedTypes.jsonc
package-lock.json

Manually update to idl@3.38.2, bcd@5.3.16

---

baselines/dom.generated.d.ts
baselines/serviceworker.generated.d.ts
baselines/sharedworker.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/removedTypes.jsonc
package-lock.json

Update to bcd@5.3.24, idl@3.39.2

---

baselines/dom.generated.d.ts
baselines/serviceworker.generated.d.ts
baselines/sharedworker.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/addedTypes.jsonc
inputfiles/overridingTypes.jsonc
package-lock.json
src/build/bcd/keep-alive.ts

🤖 Update core dependencies

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.jsonc

- use `RTCPeerConnectionIceErrorEvent` for `icecandidateerror` event type
Reference: https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/icecandidateerror_event

fix: add icecandidateerror type

---

baselines/dom.generated.d.ts
inputfiles/comments.json

Fairly simple one. Since there is no return value, the paused property should be used for testing if a media element is paused instead of the pause method.
[Looking at the spec](https://html.spec.whatwg.org/multipage/media.html#dom-media-pause-dev)
> The paused attribute represents whether the [media element](https://html.spec.whatwg.org/multipage/media.html#media-element) is paused or not.
That comment has been there 6 years, so I am not sure of the origin, but it confused me so I made the PR.
References:
https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/pause
https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/paused

Remove invalid documentation for pause method of HTMLMediaElement

---

.github/workflows/codeowners-merge.yml

This should fix auto merging. The permissions block might need `issue: write`, too, but I think that all of the PR stuff can be accessed using `pull-requests: write` by my reading of https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps?apiVersion=2022-11-28#repository-permissions-for-pull-requests

Add permissions to codeowners merge workflow

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.jsonc

According to https://html.spec.whatwg.org/multipage/form-elements.html#dom-select-type-dev: ‘Returns "`select-multiple`" if the element has a `multiple` attribute, and "`select-one`" otherwise.’

Strengthen type of `HTMLSelectElement.type`

---

.github/workflows/deploy.yml

Pushing new tag has been failing since around Feb: https://github.com/microsoft/TypeScript-DOM-lib-generator/actions/runs/8243409917/job/22543947996#step:9:71
This mimics #1688. @jakebailey

Assign contents permission to deploy CI job

---

baselines/dom.generated.d.ts
baselines/dom.iterable.generated.d.ts
baselines/serviceworker.generated.d.ts
baselines/sharedworker.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/removedTypes.jsonc
package-lock.json

Update to bcd@5.5.26,idl@3.47.2

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.jsonc
inputfiles/removedTypes.jsonc
package-lock.json

Update to webref/idl@3.48.0

---

baselines/audioworklet.generated.d.ts
baselines/audioworklet.iterable.generated.d.ts
baselines/dom.generated.d.ts
baselines/dom.iterable.generated.d.ts
baselines/serviceworker.generated.d.ts
baselines/serviceworker.iterable.generated.d.ts
baselines/sharedworker.generated.d.ts
baselines/sharedworker.iterable.generated.d.ts
baselines/webworker.generated.d.ts
baselines/webworker.iterable.generated.d.ts
package-lock.json

Massive MDN reference changes by https://github.com/mdn/browser-compat-data/pull/23481, nothing else. Reducing #1753 to make diffs clearer.

Update to bcd@5.5.36

---

baselines/audioworklet.generated.d.ts
baselines/dom.generated.d.ts
baselines/serviceworker.generated.d.ts
baselines/sharedworker.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/overridingTypes.jsonc

Modified the `URL.canParse` and `URL.parse` types to match the URL constructor type.

Update the `URL.canParse` and `URL.parse` types

---

baselines/audioworklet.generated.d.ts
baselines/dom.generated.d.ts
baselines/serviceworker.generated.d.ts
baselines/sharedworker.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/addedTypes.jsonc
inputfiles/overridingTypes.jsonc

I am working on making the Deno types match the DOM types in this repository as closely as possible (https://github.com/denoland/deno/pull/24599). I send a PR for the types that I think should be included in the TypeScript side.

Improve some types from Deno

---

package-lock.json

No feature change, just a syntax change so that it can be used in the latest Node.js without import assert support.

Update to bim@2.3.1

---

baselines/dom.generated.d.ts
baselines/serviceworker.generated.d.ts
baselines/sharedworker.generated.d.ts
baselines/ts5.5/dom.generated.d.ts
baselines/ts5.5/serviceworker.generated.d.ts
baselines/ts5.5/sharedworker.generated.d.ts
baselines/ts5.5/webworker.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/overridingTypes.jsonc
inputfiles/removedTypes.jsonc
package-lock.json
src/build/bcd/keep-alive.ts

Notable PaymentRequest additions. Thanks bot: https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1282#issuecomment-2298240055

Manually update to idl@3.52.2

---

src/test.ts

printInlineDiff prints all the text which doesn't make sense for our use case.

Use printUnifiedDiff for test

---

baselines/dom.generated.d.ts
inputfiles/overridingTypes.jsonc

Add an override for [`addIceCandidate`][]’s `candidate` parameter to allow it to be `null`, which is a special value indicating that ICE gathering is complete.
> If no `candidate` object is specified, **or its value is `null`**, an end-of-candidates signal is sent to the remote peer *[emphasis added]*
Fixes #1738.
[`addIceCandidate`]: https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/addIceCandidate

Allow `null` candidate in `RTCPeerConnection.addIceCandidate`

---

baselines/dom.generated.d.ts
baselines/ts5.5/dom.generated.d.ts
inputfiles/removedTypes.jsonc
package-lock.json

Update bcd to 5.5.49

---

baselines/dom.generated.d.ts
baselines/ts5.5/dom.generated.d.ts
inputfiles/overridingTypes.jsonc
inputfiles/removedTypes.jsonc
package-lock.json

Thanks bot: https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1282#issuecomment-2320435308

Manually update to idl@3.53.0

---

eslint.config.mjs
package-lock.json
package.json

Migrate to ESLint flat config

---

baselines/dom.generated.d.ts
baselines/ts5.5/dom.generated.d.ts
baselines/ts5.5/webworker.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/removedTypes.jsonc
package-lock.json

Update to idl@3.55.1

---

baselines/audioworklet.iterable.generated.d.ts
baselines/dom.iterable.generated.d.ts
baselines/serviceworker.iterable.generated.d.ts
baselines/sharedworker.iterable.generated.d.ts
baselines/ts5.5/audioworklet.iterable.generated.d.ts
baselines/ts5.5/dom.iterable.generated.d.ts
baselines/ts5.5/serviceworker.iterable.generated.d.ts
baselines/ts5.5/sharedworker.iterable.generated.d.ts
baselines/ts5.5/webworker.iterable.generated.d.ts
baselines/webworker.iterable.generated.d.ts
src/build/emitter.ts

The current logic is bugged, and the correct fix is not possible because of #222.
Closes #1803

Do not generate iterable signatures for static methods

---

baselines/dom.generated.d.ts
baselines/ts5.5/dom.generated.d.ts
inputfiles/overridingTypes.jsonc

Fixes https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1861

Type Canvas.toBlob/toDataURL `quality` argument as `number`

---

baselines/dom.generated.d.ts
baselines/dom.iterable.generated.d.ts
baselines/serviceworker.generated.d.ts
baselines/serviceworker.iterable.generated.d.ts
baselines/sharedworker.generated.d.ts
baselines/sharedworker.iterable.generated.d.ts
baselines/ts5.5/dom.generated.d.ts
baselines/ts5.5/dom.iterable.generated.d.ts
baselines/ts5.5/serviceworker.generated.d.ts
baselines/ts5.5/serviceworker.iterable.generated.d.ts
baselines/ts5.5/sharedworker.generated.d.ts
baselines/ts5.5/sharedworker.iterable.generated.d.ts
baselines/ts5.5/webworker.generated.d.ts
baselines/ts5.5/webworker.iterable.generated.d.ts
baselines/webworker.generated.d.ts
baselines/webworker.iterable.generated.d.ts
inputfiles/overridingTypes.jsonc

As a follow up for #1594, I'd like to add the object form of the Edwards curve identifier (`{ name: "Ed25519" }`) to complement the string form (`"Ed25519"`).
This will prevent having to constantly refine the return type of `generateKey` when all this API ever returns is a `CryptoKeyPair` when used with this algorithm.
```ts
const key = await crypto.subtle.generateKey(
{ name: 'Ed25519' },
false, /* extractable */
['sign', 'verify'],
) as CryptoKeyPair;
```
See #1594 for more.

Add object form of `Ed25519` overload for `SubtleCrypto#generateKey`

---

baselines/audioworklet.generated.d.ts
baselines/dom.generated.d.ts
baselines/serviceworker.generated.d.ts
baselines/sharedworker.generated.d.ts
baselines/ts5.5/audioworklet.generated.d.ts
baselines/ts5.5/dom.generated.d.ts
baselines/ts5.5/serviceworker.generated.d.ts
baselines/ts5.5/sharedworker.generated.d.ts
baselines/ts5.5/webworker.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/overridingTypes.jsonc

The override did not get added when the new mixin was introduced to Worker and MessagePort.

MessageEventTarget's events have type MessageEvent

---

baselines/dom.generated.d.ts
baselines/ts5.5/dom.generated.d.ts
inputfiles/overridingTypes.jsonc

Fixes: https://github.com/microsoft/TypeScript/issues/60940

fix: `fetchPriority` type for `HTMLImageElement`, `HTMLLinkElement`, and `HTMLScriptElement`

---

baselines/audioworklet.generated.d.ts
baselines/dom.generated.d.ts
baselines/serviceworker.generated.d.ts
baselines/sharedworker.generated.d.ts
baselines/webworker.generated.d.ts
src/build/emitter.ts

lib.dom.d.ts ubiquitously uses `Promise<void>` for promises not resolving
to undefined. It has done this for a long time.
When the generator was written, there were 0 or 1 (I can't quite tell)
places where this type of promise occured outside of a function return
value. However, Web Streams are now widely supported, and they have
properties that are promises that resolve to no value. These are
currently typed as `Promise<undefined>`. This commit changes them to be
typed as `Promise<void>`, to align with the rest of lib.dom.d.ts.
There are 5 readonly properties that are impacted by this change.

Consistently use Promise<void> instead of Promise<undefined>

---

package.json

I did a checkout of the repo, ran `npm install` and `npm test` and got:
```
deploy/deployChangedPackages.js:12:39 - error TS2307: Cannot find module '../lib/changelog.js' or its corresponding type declarations.
12 import { generateChangelogFrom } from "../lib/changelog.js";
~~~~~~~~~~~~~~~~~~~~~
deploy/versionChangelog.js:5:52 - error TS2307: Cannot find module '../lib/changelog.js' or its corresponding type declarations.
5 import { gitShowFile, generateChangelogFrom } from "../lib/changelog.js";
~~~~~~~~~~~~~~~~~~~~~
```
This is because eslint runs on files that import from files which has not been built initially, turning these two around (building before linting) seems like a harmless fix.

Fix running "test" in a clean repo

---

baselines/audioworklet.generated.d.ts
baselines/dom.generated.d.ts
baselines/serviceworker.generated.d.ts
baselines/sharedworker.generated.d.ts
baselines/ts5.5/audioworklet.generated.d.ts
baselines/ts5.5/dom.generated.d.ts
baselines/ts5.5/serviceworker.generated.d.ts
baselines/ts5.5/sharedworker.generated.d.ts
baselines/ts5.5/webworker.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/overridingTypes.jsonc
src/build/emitter.ts
src/build/types.d.ts

This is needed after all. I incorrectly reverted it in my previous PR.

Override MessageEventTarget's this parameters

---

package.json

Apparently this package name was name squatted on npm by a malicious actor: https://github.com/advisories/GHSA-5h3m-q8pm-rw64.
The issue is that anyone importing this package gets a "**critical** severity vulnerability" because of the package name.  Making the package name scoped to @microsoft avoids any confusion today, and guards against any [potential future npm substitution attacks](https://github.blog/security/supply-chain-security/avoiding-npm-substitution-attacks/).

Make package name scoped to @typescript

---

baselines/audioworklet.generated.d.ts
baselines/dom.generated.d.ts
baselines/serviceworker.generated.d.ts
baselines/sharedworker.generated.d.ts
baselines/ts5.5/audioworklet.generated.d.ts
baselines/ts5.5/dom.generated.d.ts
baselines/ts5.5/serviceworker.generated.d.ts
baselines/ts5.5/sharedworker.generated.d.ts
baselines/ts5.5/webworker.generated.d.ts
baselines/webworker.generated.d.ts
package-lock.json
src/build/emitter.ts

This makes the output more stable and diff-friendly.

Sort namespaces before emitting

---

src/build/emitter.ts

I believe this is correct, static members from global polluters shouldn't show up as globals.

Emit only instance members from global polluters

---

baselines/dom.generated.d.ts
baselines/ts5.5/dom.generated.d.ts
inputfiles/removedTypes.jsonc
package-lock.json

Update to idl@3.59.4

---

baselines/audioworklet.generated.d.ts
baselines/dom.generated.d.ts
baselines/serviceworker.generated.d.ts
baselines/sharedworker.generated.d.ts
baselines/ts5.5/audioworklet.generated.d.ts
baselines/ts5.5/dom.generated.d.ts
baselines/ts5.5/serviceworker.generated.d.ts
baselines/ts5.5/sharedworker.generated.d.ts
baselines/ts5.5/webworker.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/addedTypes.jsonc

The IDL specifies for `ReadableStreamReadResult` that the `value` property is always present. If the stream is cancelled, then this property won't be absent, but will be present with the value `undefined`. (This differs from _eg._ the iterator protocol, where a result object's `value` property may indeed be absent if the iterator is closed.)
The difference is only really manifest when `exactOptionalPropertyTypes` is enabled, but where it is, `ReadableStreamReadDoneResult` is currently divergent from the web standard.

Correct optionality of `ReadableStreamReadDoneResult.value`

---

baselines/dom.generated.d.ts
baselines/ts5.5/dom.generated.d.ts
inputfiles/overridingTypes.jsonc

The multiple implementation requirement is achieved in 2024-09.
Closes #1892

Restore StartViewTransitionOptions

---

inputfiles/overridingTypes.jsonc

It has been noted in SolidJS discord that the interface for `contextmenu` and `auxclick` events is `PointerEvent` not `MouseEvent`.  MDN supports 
- https://developer.mozilla.org/en-US/docs/Web/API/Element/auxclick_event 
- https://developer.mozilla.org/en-US/docs/Web/API/Element/contextmenu_event
The file being updated here has other 10 sibling entries also for the same event `PointerEvent`, so I am adding 2 more.
Now, I'm not completely sure why this is still _outdated?_/needs manual overriding, may be worth to look at that. 
Thanks!

Update overridingTypes.jsonc to add `PointerEvent` to `contextmenu` and `auxclick`

---

baselines/dom.generated.d.ts
baselines/serviceworker.generated.d.ts
baselines/sharedworker.generated.d.ts
baselines/ts5.5/dom.generated.d.ts
baselines/ts5.5/serviceworker.generated.d.ts
baselines/ts5.5/sharedworker.generated.d.ts
baselines/ts5.5/webworker.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/overridingTypes.jsonc

Hello :)
I have allowed `IDBObjectStore` to be null as requested in https://github.com/microsoft/TypeScript/issues/61209

fix(IDBObjectStore): Allow keyPath to be null

---

baselines/dom.generated.d.ts
baselines/ts5.5/dom.generated.d.ts
inputfiles/addedTypes.jsonc

This PR is adding type of `pageswap` and `pagereveal` event callback args on window event handler property and `addEventListener`. 
Both of them are already supported by Chromium and Webkit.
> [!NOTE]
> PageSwap and PageReveal Event interfaces are added at this PR (https://github.com/microsoft/TypeScript/pull/60987), but event handler callback args is still typed as `Event`.

DOM: Add Support for pageswap and pagereveal event on window

---

deploy/readmes/web.md
deploy/readmes/webworker.md

https://www.typescriptlang.org/tsconfig/#libReplacement is a better documentation page for that flag, especially given we're planning on turning this feature off by default.

Swap link to lib replacement to libReplacement flag

---

baselines/dom.generated.d.ts
baselines/serviceworker.generated.d.ts
baselines/ts5.5/dom.generated.d.ts
baselines/ts5.5/serviceworker.generated.d.ts
baselines/ts5.5/webworker.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/removedTypes.jsonc

fix: Unexpected Safari-specific event init options

---

.github/workflows/update-core-deps.yml
README.md
package.json

Hello! 🙂
I’ve added a new `generate` command to the `package.json` scripts. This change will allow contributors to quickly run the build and baseline acceptance process with a single command, improving workflow efficiency.
Instead of manually running:
```bash
npm run build && npm run baseline-accept
```
Contributors can now simply execute:
```bash
npm run generate
```
Here’s how the updated `scripts` section will look:
```json
"scripts": {
"generate": "npm run build && npm run baseline-accept"
}
```
This small change should help make the development process smoother for everyone. Let me know if you have any questions or suggestions!

Add `generate` command for faster build and baseline acceptance

---

.github/workflows/deploy.yml

Hello!
I’ve added a safeguard to ensure that the NPM deploy action only runs in the **main repository**.
The workflow was being triggered **daily in my fork**, which obviously failed because the NPM token (`NODE_AUTH_TOKEN`) isn’t available in forks.
Added the following condition to the job:
```yaml
if: github.repository == 'your-username/your-repo-name'
```
This ensures that the deploy job only runs in the main repo, and not in forks. If someone removes that line, the job might start triggering (and failing) in forks again — so it's important to keep it!

Prevent Deploy Workflow from Running in Forks

---

baselines/dom.generated.d.ts
baselines/ts5.5/dom.generated.d.ts
baselines/ts5.6/dom.generated.d.ts
inputfiles/addedTypes.jsonc

This PR aim to update `toggle` and `beforetoggle` event callback definition.
Interface `ToggleEvent` on `toggle` and `beforetoggle` is already supported by Chromium / Webkit / Gecko. 
refs:
- https://developer.mozilla.org/en-US/docs/Web/API/ToggleEvent 
- https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/toggle_event 
- https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/beforetoggle_event 
resolve #1969

Support `toggle` and `beforetoggle` event types

---

baselines/dom.generated.d.ts
baselines/ts5.5/dom.generated.d.ts
baselines/ts5.6/dom.generated.d.ts
inputfiles/overridingTypes.jsonc

I have updated the alert method to take a string.
fixes #1626

fix: update alert method signature to accept string type

---

baselines/dom.generated.d.ts
baselines/ts5.5/dom.generated.d.ts
baselines/ts5.6/dom.generated.d.ts
inputfiles/overridingTypes.jsonc

This reverts commit 3263db83c494706b220fc8d9ed5fcaac422d65f0, to make https://github.com/microsoft/TypeScript/pull/61647 less painful. See https://github.com/microsoft/TypeScript/pull/61647#issuecomment-2852450040.
cc @rbuckton

Revert "fix: update alert method signature to accept string type"

---

baselines/dom.generated.d.ts
baselines/ts5.5/dom.generated.d.ts
baselines/ts5.6/dom.generated.d.ts
inputfiles/addedTypes.jsonc
inputfiles/overridingTypes.jsonc

I have converted MouseEvent to PointerEvent in some occurrences.
References:
1- https://w3c.github.io/uievents/#event-type-click
2 - https://caniuse.com/?search=PointerEvent
3 - https://developer.mozilla.org/en-US/docs/Web/API/Element/click_event
Solves:
1- https://github.com/microsoft/TypeScript/issues/60746
2 - https://github.com/microsoft/TypeScript/pull/61647#issuecomment-2848634352

fix: change event types from MouseEvent to PointerEvent

---

baselines/dom.generated.d.ts
baselines/ts5.5/dom.generated.d.ts
baselines/ts5.6/dom.generated.d.ts
inputfiles/removedTypes.jsonc
package-lock.json

Update to webref/idl@3.63.0

---

baselines/dom.generated.d.ts
baselines/serviceworker.generated.d.ts
baselines/sharedworker.generated.d.ts
baselines/ts5.5/dom.generated.d.ts
baselines/ts5.5/serviceworker.generated.d.ts
baselines/ts5.5/sharedworker.generated.d.ts
baselines/ts5.5/webworker.generated.d.ts
baselines/ts5.6/dom.generated.d.ts
baselines/ts5.6/serviceworker.generated.d.ts
baselines/ts5.6/sharedworker.generated.d.ts
baselines/ts5.6/webworker.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/overridingTypes.jsonc

Partial fix for https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/1194

Partially fix `crypto.getRandomValues` type param

---

src/build/emitter.ts

Solves the failing build of #2047

Refactor property name handling in emitWebIdl function to support hyphenated names

---

baselines/dom.generated.d.ts
baselines/serviceworker.generated.d.ts
baselines/sharedworker.generated.d.ts
baselines/ts5.5/dom.generated.d.ts
baselines/ts5.5/serviceworker.generated.d.ts
baselines/ts5.5/sharedworker.generated.d.ts
baselines/ts5.5/webworker.generated.d.ts
baselines/ts5.6/dom.generated.d.ts
baselines/ts5.6/serviceworker.generated.d.ts
baselines/ts5.6/sharedworker.generated.d.ts
baselines/ts5.6/webworker.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/overridingTypes.jsonc
package-lock.json

But disable others, there will be followups.
Notification.badge is removed by https://github.com/mdn/browser-compat-data/pull/27059.

Add CSS properties from BCD 6.0.24

---

baselines/dom.generated.d.ts
baselines/ts5.5/dom.generated.d.ts
baselines/ts5.6/dom.generated.d.ts
inputfiles/addedTypes.jsonc
inputfiles/overridingTypes.jsonc
package-lock.json
package.json
src/build/bcd/keep-alive.ts
src/build/webref/css.ts

Corresponds to https://github.com/w3c/csswg-drafts/pull/9686.

Use CSSStyleProperties to prepare for bcd 6.0.24

---

baselines/dom.generated.d.ts
baselines/ts5.5/dom.generated.d.ts
baselines/ts5.6/dom.generated.d.ts
inputfiles/removedTypes.jsonc
package-lock.json

Update to idl@3.65.5

---

deploy/createTypesPackages.js
deploy/migrate.js

It has not been needed for years but I never noticed because I forgot about these scripts and never used them.
This means that the types packages used for overriding the default DOM types have had AbortSignal.abort incorrectly disabled all this time, but it's rarely used (only a few repos per million at Google, at least), so nobody ever complained about it.
In theory we could need the post-processing capability in the future, but it's trivial to bring back or to write again. That's why I deleted it outright.

Remove .d.ts post-process in deploy+migrate scripts

---

baselines/audioworklet.generated.d.ts
baselines/dom.generated.d.ts
baselines/serviceworker.generated.d.ts
baselines/sharedworker.generated.d.ts
baselines/ts5.5/audioworklet.generated.d.ts
baselines/ts5.5/dom.generated.d.ts
baselines/ts5.5/serviceworker.generated.d.ts
baselines/ts5.5/sharedworker.generated.d.ts
baselines/ts5.5/webworker.generated.d.ts
baselines/ts5.6/audioworklet.generated.d.ts
baselines/ts5.6/dom.generated.d.ts
baselines/ts5.6/serviceworker.generated.d.ts
baselines/ts5.6/sharedworker.generated.d.ts
baselines/ts5.6/webworker.generated.d.ts
baselines/webworker.generated.d.ts
src/build/mdn-comments.ts

This PR adds comments for WebAssembly
closes #2003

Generate comments for WebAssembly

---

src/build/patches.ts

Before @Bashamega opens another PR 😜

Add more types and return value from handleEnum/Mixin

---

baselines/dom.generated.d.ts
baselines/serviceworker.generated.d.ts
baselines/sharedworker.generated.d.ts
baselines/ts5.5/dom.generated.d.ts
baselines/ts5.5/serviceworker.generated.d.ts
baselines/ts5.5/sharedworker.generated.d.ts
baselines/ts5.5/webworker.generated.d.ts
baselines/ts5.6/dom.generated.d.ts
baselines/ts5.6/serviceworker.generated.d.ts
baselines/ts5.6/sharedworker.generated.d.ts
baselines/ts5.6/webworker.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/overridingTypes.jsonc
inputfiles/removedTypes.jsonc
package-lock.json

Update to bcd@6.0.37, idl@3.66.1

---

inputfiles/overridingTypes.jsonc
inputfiles/patches/dom.kdl
inputfiles/patches/html.kdl

Migrate ImageOrientation to KDL

---

baselines/dom.generated.d.ts
baselines/serviceworker.generated.d.ts
baselines/sharedworker.generated.d.ts
baselines/ts5.5/dom.generated.d.ts
baselines/ts5.5/serviceworker.generated.d.ts
baselines/ts5.5/sharedworker.generated.d.ts
baselines/ts5.5/webworker.generated.d.ts
baselines/ts5.6/dom.generated.d.ts
baselines/ts5.6/serviceworker.generated.d.ts
baselines/ts5.6/sharedworker.generated.d.ts
baselines/ts5.6/webworker.generated.d.ts
baselines/webworker.generated.d.ts
inputfiles/overridingTypes.jsonc
package-lock.json
src/build/bcd/keep-alive.ts

To consume #2149 (and #2163) progressively.

Update to bcd@7.1.6

---

baselines/dom.generated.d.ts
baselines/ts5.5/dom.generated.d.ts
baselines/ts5.6/dom.generated.d.ts
inputfiles/patches/cssom.kdl
src/build/emitter.ts
src/build/patches.ts
src/build/types.ts
src/build/widlprocess.ts
unittests/files/css-style.ts

This should reduce DT breakage. But note that this would make `CSSPageDescriptors extends CSSStyleDeclaration` to `false`. Authors would need to use CSSStyleDeclarationBase for that.

Introduce CSSStyleDeclarationBase

---

inputfiles/addedTypes.jsonc

This is now in the IDL, and the emitter is warning about the duplicate property.

Remove redundant SVGStyleElement override
